// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="TOP_fuct,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.419200,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=38,HLS_SYN_DSP=14,HLS_SYN_FF=6216,HLS_SYN_LUT=13665,HLS_VERSION=2018_3}" *)

module TOP_fuct (
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        ap_clk,
        ap_rst_n,
        INPUT_STREAM_TDATA,
        INPUT_STREAM_TKEEP,
        INPUT_STREAM_TSTRB,
        INPUT_STREAM_TUSER,
        INPUT_STREAM_TLAST,
        INPUT_STREAM_TID,
        INPUT_STREAM_TDEST,
        OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TUSER,
        OUTPUT_STREAM_TLAST,
        OUTPUT_STREAM_TID,
        OUTPUT_STREAM_TDEST,
        INPUT_STREAM_TVALID,
        INPUT_STREAM_TREADY
);

parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
input   ap_clk;
input   ap_rst_n;
input  [31:0] INPUT_STREAM_TDATA;
input  [3:0] INPUT_STREAM_TKEEP;
input  [3:0] INPUT_STREAM_TSTRB;
input  [0:0] INPUT_STREAM_TUSER;
input  [0:0] INPUT_STREAM_TLAST;
input  [0:0] INPUT_STREAM_TID;
input  [0:0] INPUT_STREAM_TDEST;
input  [31:0] OUTPUT_STREAM_TDATA;
input  [3:0] OUTPUT_STREAM_TKEEP;
input  [3:0] OUTPUT_STREAM_TSTRB;
input  [0:0] OUTPUT_STREAM_TUSER;
input  [0:0] OUTPUT_STREAM_TLAST;
input  [0:0] OUTPUT_STREAM_TID;
input  [0:0] OUTPUT_STREAM_TDEST;
input   INPUT_STREAM_TVALID;
output   INPUT_STREAM_TREADY;

 reg    ap_rst_n_inv;
wire   [31:0] rows;
wire   [31:0] cols;
wire   [0:0] SobOvlyIma_Strt_i_q0;
wire   [0:0] SobOvlyIma_Strt_i_q1;
wire   [0:0] SobOvlyIma_Strt_t_q0;
wire   [0:0] SobOvlyIma_Strt_t_q1;
wire   [0:0] XsOvImStrtLoc_i_q0;
wire   [0:0] XsOvImStrtLoc_i_q1;
wire   [0:0] XsOvImStrtLoc_t_q0;
wire   [0:0] XsOvImStrtLoc_t_q1;
wire   [31:0] K_q0;
wire   [31:0] B_q0;
wire   [31:0] NumPoint_q0;
wire    TOP_fuct_entry3_U0_ap_start;
wire    TOP_fuct_entry3_U0_ap_done;
wire    TOP_fuct_entry3_U0_ap_continue;
wire    TOP_fuct_entry3_U0_ap_idle;
wire    TOP_fuct_entry3_U0_ap_ready;
wire    TOP_fuct_entry3_U0_start_out;
wire    TOP_fuct_entry3_U0_start_write;
wire   [31:0] TOP_fuct_entry3_U0_rows_out_din;
wire    TOP_fuct_entry3_U0_rows_out_write;
wire   [31:0] TOP_fuct_entry3_U0_cols_out_din;
wire    TOP_fuct_entry3_U0_cols_out_write;
wire    TOP_fuct_entry226_U0_ap_start;
wire    TOP_fuct_entry226_U0_ap_done;
wire    TOP_fuct_entry226_U0_ap_continue;
wire    TOP_fuct_entry226_U0_ap_idle;
wire    TOP_fuct_entry226_U0_ap_ready;
wire    TOP_fuct_entry226_U0_start_out;
wire    TOP_fuct_entry226_U0_start_write;
wire    TOP_fuct_entry226_U0_rows_read;
wire    TOP_fuct_entry226_U0_cols_read;
wire   [31:0] TOP_fuct_entry226_U0_rows_out_din;
wire    TOP_fuct_entry226_U0_rows_out_write;
wire   [31:0] TOP_fuct_entry226_U0_cols_out_din;
wire    TOP_fuct_entry226_U0_cols_out_write;
wire    Loop_memset_SobOvlyI_U0_ap_start;
wire    Loop_memset_SobOvlyI_U0_ap_done;
wire    Loop_memset_SobOvlyI_U0_ap_continue;
wire    Loop_memset_SobOvlyI_U0_ap_idle;
wire    Loop_memset_SobOvlyI_U0_ap_ready;
wire   [0:0] Loop_memset_SobOvlyI_U0_SobOvlyIma_Strt_address0;
wire    Loop_memset_SobOvlyI_U0_SobOvlyIma_Strt_ce0;
wire    Loop_memset_SobOvlyI_U0_SobOvlyIma_Strt_we0;
wire   [0:0] Loop_memset_SobOvlyI_U0_SobOvlyIma_Strt_d0;
wire    ap_channel_done_SobOvlyIma_Strt;
wire    Loop_memset_SobOvlyI_U0_SobOvlyIma_Strt_full_n;
wire    Block_TOP_fuct_memin_U0_ap_start;
wire    Block_TOP_fuct_memin_U0_start_full_n;
wire    Block_TOP_fuct_memin_U0_ap_done;
wire    Block_TOP_fuct_memin_U0_ap_continue;
wire    Block_TOP_fuct_memin_U0_ap_idle;
wire    Block_TOP_fuct_memin_U0_ap_ready;
wire    Block_TOP_fuct_memin_U0_start_out;
wire    Block_TOP_fuct_memin_U0_start_write;
wire    Block_TOP_fuct_memin_U0_rows_read;
wire    Block_TOP_fuct_memin_U0_cols_read;
wire   [31:0] Block_TOP_fuct_memin_U0_rows_out_din;
wire    Block_TOP_fuct_memin_U0_rows_out_write;
wire   [31:0] Block_TOP_fuct_memin_U0_ImgRgb_Datsrc_rows_V_out_din;
wire    Block_TOP_fuct_memin_U0_ImgRgb_Datsrc_rows_V_out_write;
wire   [31:0] Block_TOP_fuct_memin_U0_cols_out_din;
wire    Block_TOP_fuct_memin_U0_cols_out_write;
wire   [31:0] Block_TOP_fuct_memin_U0_ImgRgb_Datsrc_cols_V_out_din;
wire    Block_TOP_fuct_memin_U0_ImgRgb_Datsrc_cols_V_out_write;
wire   [31:0] Block_TOP_fuct_memin_U0_ImgGry_Datsrc_rows_V_out_din;
wire    Block_TOP_fuct_memin_U0_ImgGry_Datsrc_rows_V_out_write;
wire   [31:0] Block_TOP_fuct_memin_U0_ImgGry_Datsrc_cols_V_out_din;
wire    Block_TOP_fuct_memin_U0_ImgGry_Datsrc_cols_V_out_write;
wire   [8:0] Block_TOP_fuct_memin_U0_ImgGry_Datcop_rows_V_out_din;
wire    Block_TOP_fuct_memin_U0_ImgGry_Datcop_rows_V_out_write;
wire   [9:0] Block_TOP_fuct_memin_U0_ImgGry_Datcop_cols_V_out_din;
wire    Block_TOP_fuct_memin_U0_ImgGry_Datcop_cols_V_out_write;
wire   [8:0] Block_TOP_fuct_memin_U0_ImgGry_Threh_sp_rows_V_out_din;
wire    Block_TOP_fuct_memin_U0_ImgGry_Threh_sp_rows_V_out_write;
wire   [9:0] Block_TOP_fuct_memin_U0_ImgGry_Threh_sp_cols_V_out_din;
wire    Block_TOP_fuct_memin_U0_ImgGry_Threh_sp_cols_V_out_write;
wire   [8:0] Block_TOP_fuct_memin_U0_ImgGry_Threh_cz_rows_V_out_din;
wire    Block_TOP_fuct_memin_U0_ImgGry_Threh_cz_rows_V_out_write;
wire   [9:0] Block_TOP_fuct_memin_U0_ImgGry_Threh_cz_cols_V_out_din;
wire    Block_TOP_fuct_memin_U0_ImgGry_Threh_cz_cols_V_out_write;
wire   [8:0] Block_TOP_fuct_memin_U0_ImgGry_Ovlaycz_rows_V_out_din;
wire    Block_TOP_fuct_memin_U0_ImgGry_Ovlaycz_rows_V_out_write;
wire   [9:0] Block_TOP_fuct_memin_U0_ImgGry_Ovlaycz_cols_V_out_din;
wire    Block_TOP_fuct_memin_U0_ImgGry_Ovlaycz_cols_V_out_write;
wire    Loop_memset_XsOvImSt_U0_ap_start;
wire    Loop_memset_XsOvImSt_U0_ap_done;
wire    Loop_memset_XsOvImSt_U0_ap_continue;
wire    Loop_memset_XsOvImSt_U0_ap_idle;
wire    Loop_memset_XsOvImSt_U0_ap_ready;
wire   [0:0] Loop_memset_XsOvImSt_U0_XsOvImStrtLoc_address0;
wire    Loop_memset_XsOvImSt_U0_XsOvImStrtLoc_ce0;
wire    Loop_memset_XsOvImSt_U0_XsOvImStrtLoc_we0;
wire   [0:0] Loop_memset_XsOvImSt_U0_XsOvImStrtLoc_d0;
wire    ap_channel_done_XsOvImStrtLoc;
wire    Loop_memset_XsOvImSt_U0_XsOvImStrtLoc_full_n;
wire    AXIvideo2Mat_U0_ap_start;
wire    AXIvideo2Mat_U0_ap_done;
wire    AXIvideo2Mat_U0_ap_continue;
wire    AXIvideo2Mat_U0_ap_idle;
wire    AXIvideo2Mat_U0_ap_ready;
wire    AXIvideo2Mat_U0_start_out;
wire    AXIvideo2Mat_U0_start_write;
wire    AXIvideo2Mat_U0_INPUT_STREAM_TREADY;
wire    AXIvideo2Mat_U0_img_rows_V_read;
wire    AXIvideo2Mat_U0_img_cols_V_read;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_0_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_0_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_1_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_1_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_2_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_2_V_write;
wire   [31:0] AXIvideo2Mat_U0_img_rows_V_out_din;
wire    AXIvideo2Mat_U0_img_rows_V_out_write;
wire   [31:0] AXIvideo2Mat_U0_img_cols_V_out_din;
wire    AXIvideo2Mat_U0_img_cols_V_out_write;
wire    CvtColor_U0_ap_start;
wire    CvtColor_U0_ap_done;
wire    CvtColor_U0_ap_continue;
wire    CvtColor_U0_ap_idle;
wire    CvtColor_U0_ap_ready;
wire    CvtColor_U0_start_out;
wire    CvtColor_U0_start_write;
wire    CvtColor_U0_p_src_rows_V_read;
wire    CvtColor_U0_p_src_cols_V_read;
wire    CvtColor_U0_p_src_data_stream_0_V_read;
wire    CvtColor_U0_p_src_data_stream_1_V_read;
wire    CvtColor_U0_p_src_data_stream_2_V_read;
wire   [7:0] CvtColor_U0_p_dst_data_stream_V_din;
wire    CvtColor_U0_p_dst_data_stream_V_write;
wire    Duplicate219_U0_ap_start;
wire    Duplicate219_U0_ap_done;
wire    Duplicate219_U0_ap_continue;
wire    Duplicate219_U0_ap_idle;
wire    Duplicate219_U0_ap_ready;
wire    Duplicate219_U0_src_rows_V_read;
wire    Duplicate219_U0_src_cols_V_read;
wire    Duplicate219_U0_src_data_stream_V_read;
wire   [7:0] Duplicate219_U0_dst1_data_stream_V_din;
wire    Duplicate219_U0_dst1_data_stream_V_write;
wire   [7:0] Duplicate219_U0_dst2_data_stream_V;
wire    Duplicate219_U0_dst2_data_stream_V_ap_vld;
wire    CopImage220_U0_ap_start;
wire    CopImage220_U0_ap_done;
wire    CopImage220_U0_ap_continue;
wire    CopImage220_U0_ap_idle;
wire    CopImage220_U0_ap_ready;
wire    CopImage220_U0_src_data_stream_V_read;
wire   [7:0] CopImage220_U0_dst_data_stream_V_din;
wire    CopImage220_U0_dst_data_stream_V_write;
wire    CopImage220_U0_HEIGHT_read;
wire    CopImage220_U0_WIDTH_read;
wire    Duplicate221_U0_ap_start;
wire    Duplicate221_U0_start_full_n;
wire    Duplicate221_U0_ap_done;
wire    Duplicate221_U0_ap_continue;
wire    Duplicate221_U0_ap_idle;
wire    Duplicate221_U0_ap_ready;
wire    Duplicate221_U0_start_out;
wire    Duplicate221_U0_start_write;
wire    Duplicate221_U0_src_rows_V_read;
wire    Duplicate221_U0_src_cols_V_read;
wire    Duplicate221_U0_src_data_stream_V_read;
wire   [7:0] Duplicate221_U0_dst1_data_stream_V_din;
wire    Duplicate221_U0_dst1_data_stream_V_write;
wire   [7:0] Duplicate221_U0_dst2_data_stream_V_din;
wire    Duplicate221_U0_dst2_data_stream_V_write;
wire    Sobel_U0_ap_start;
wire    Sobel_U0_ap_done;
wire    Sobel_U0_ap_continue;
wire    Sobel_U0_ap_idle;
wire    Sobel_U0_ap_ready;
wire    Sobel_U0_p_src_data_stream_V_read;
wire   [7:0] Sobel_U0_p_dst_data_stream_V_din;
wire    Sobel_U0_p_dst_data_stream_V_write;
wire    Sobel_1_U0_ap_start;
wire    Sobel_1_U0_ap_done;
wire    Sobel_1_U0_ap_continue;
wire    Sobel_1_U0_ap_idle;
wire    Sobel_1_U0_ap_ready;
wire    Sobel_1_U0_p_src_data_stream_V_read;
wire   [7:0] Sobel_1_U0_p_dst_data_stream_V_din;
wire    Sobel_1_U0_p_dst_data_stream_V_write;
wire    Threshold222_U0_ap_start;
wire    Threshold222_U0_ap_done;
wire    Threshold222_U0_ap_continue;
wire    Threshold222_U0_ap_idle;
wire    Threshold222_U0_ap_ready;
wire    Threshold222_U0_start_out;
wire    Threshold222_U0_start_write;
wire    Threshold222_U0_src_data_stream_V_read;
wire    Threshold222_U0_dst_rows_V_read;
wire    Threshold222_U0_dst_cols_V_read;
wire   [7:0] Threshold222_U0_dst_data_stream_V_din;
wire    Threshold222_U0_dst_data_stream_V_write;
wire    Threshold_U0_ap_start;
wire    Threshold_U0_ap_done;
wire    Threshold_U0_ap_continue;
wire    Threshold_U0_ap_idle;
wire    Threshold_U0_ap_ready;
wire    Threshold_U0_src_data_stream_V_read;
wire    Threshold_U0_dst_rows_V_read;
wire    Threshold_U0_dst_cols_V_read;
wire   [7:0] Threshold_U0_dst_data_stream_V_din;
wire    Threshold_U0_dst_data_stream_V_write;
wire    filtrel_kernel_U0_ap_start;
wire    filtrel_kernel_U0_ap_done;
wire    filtrel_kernel_U0_ap_continue;
wire    filtrel_kernel_U0_ap_idle;
wire    filtrel_kernel_U0_ap_ready;
wire    filtrel_kernel_U0_src_data_stream_V_read;
wire   [7:0] filtrel_kernel_U0_dst_data_stream_V_din;
wire    filtrel_kernel_U0_dst_data_stream_V_write;
wire    OvlayImage223_U0_ap_start;
wire    OvlayImage223_U0_ap_done;
wire    OvlayImage223_U0_ap_continue;
wire    OvlayImage223_U0_ap_idle;
wire    OvlayImage223_U0_ap_ready;
wire    OvlayImage223_U0_start_out;
wire    OvlayImage223_U0_start_write;
wire    OvlayImage223_U0_src_data_stream_V_read;
wire    OvlayImage223_U0_ovlaysrc_data_stream_V_read;
wire   [7:0] OvlayImage223_U0_dst_data_stream_V_din;
wire    OvlayImage223_U0_dst_data_stream_V_write;
wire   [0:0] OvlayImage223_U0_StartLoc_address0;
wire    OvlayImage223_U0_StartLoc_ce0;
wire   [0:0] OvlayImage223_U0_StartLoc_address1;
wire    OvlayImage223_U0_StartLoc_ce1;
wire    Duplicate_U0_ap_start;
wire    Duplicate_U0_ap_done;
wire    Duplicate_U0_ap_continue;
wire    Duplicate_U0_ap_idle;
wire    Duplicate_U0_ap_ready;
wire    Duplicate_U0_start_out;
wire    Duplicate_U0_start_write;
wire    Duplicate_U0_src_rows_V_read;
wire    Duplicate_U0_src_cols_V_read;
wire    Duplicate_U0_src_data_stream_V_read;
wire   [7:0] Duplicate_U0_dst1_data_stream_V_din;
wire    Duplicate_U0_dst1_data_stream_V_write;
wire   [7:0] Duplicate_U0_dst2_data_stream_V_din;
wire    Duplicate_U0_dst2_data_stream_V_write;
wire    CopImage224_U0_ap_start;
wire    CopImage224_U0_ap_done;
wire    CopImage224_U0_ap_continue;
wire    CopImage224_U0_ap_idle;
wire    CopImage224_U0_ap_ready;
wire    CopImage224_U0_start_out;
wire    CopImage224_U0_start_write;
wire    CopImage224_U0_src_data_stream_V_read;
wire   [7:0] CopImage224_U0_dst_data_stream_V_din;
wire    CopImage224_U0_dst_data_stream_V_write;
wire    filtrel_kernelXS_U0_ap_start;
wire    filtrel_kernelXS_U0_ap_done;
wire    filtrel_kernelXS_U0_ap_continue;
wire    filtrel_kernelXS_U0_ap_idle;
wire    filtrel_kernelXS_U0_ap_ready;
wire    filtrel_kernelXS_U0_src_data_stream_V_read;
wire   [7:0] filtrel_kernelXS_U0_dst_data_stream_V_din;
wire    filtrel_kernelXS_U0_dst_data_stream_V_write;
wire    OvlayImage225_U0_ap_start;
wire    OvlayImage225_U0_ap_done;
wire    OvlayImage225_U0_ap_continue;
wire    OvlayImage225_U0_ap_idle;
wire    OvlayImage225_U0_ap_ready;
wire    OvlayImage225_U0_start_out;
wire    OvlayImage225_U0_start_write;
wire    OvlayImage225_U0_src_data_stream_V_read;
wire    OvlayImage225_U0_ovlaysrc_data_stream_V_read;
wire   [7:0] OvlayImage225_U0_dst_data_stream_V_din;
wire    OvlayImage225_U0_dst_data_stream_V_write;
wire   [0:0] OvlayImage225_U0_StartLoc_address0;
wire    OvlayImage225_U0_StartLoc_ce0;
wire   [0:0] OvlayImage225_U0_StartLoc_address1;
wire    OvlayImage225_U0_StartLoc_ce1;
wire    SeekPoint_U0_ap_start;
wire    SeekPoint_U0_ap_done;
wire    SeekPoint_U0_ap_continue;
wire    SeekPoint_U0_ap_idle;
wire    SeekPoint_U0_ap_ready;
wire    SeekPoint_U0_src_data_stream_V_read;
wire   [5:0] SeekPoint_U0_K_address0;
wire    SeekPoint_U0_K_ce0;
wire    SeekPoint_U0_K_we0;
wire   [31:0] SeekPoint_U0_K_d0;
wire   [5:0] SeekPoint_U0_B_address0;
wire    SeekPoint_U0_B_ce0;
wire    SeekPoint_U0_B_we0;
wire   [31:0] SeekPoint_U0_B_d0;
wire   [5:0] SeekPoint_U0_NumPoint_address0;
wire    SeekPoint_U0_NumPoint_ce0;
wire    SeekPoint_U0_NumPoint_we0;
wire   [31:0] SeekPoint_U0_NumPoint_d0;
wire    SobOvlyIma_Strt_i_full_n;
wire    SobOvlyIma_Strt_t_empty_n;
wire   [0:0] SobOvlyIma_Strt_t_d1;
wire    SobOvlyIma_Strt_t_we1;
wire    XsOvImStrtLoc_i_full_n;
wire    XsOvImStrtLoc_t_empty_n;
wire   [0:0] XsOvImStrtLoc_t_d1;
wire    XsOvImStrtLoc_t_we1;
wire    rows_c1_full_n;
wire   [31:0] rows_c1_dout;
wire    rows_c1_empty_n;
wire    cols_c2_full_n;
wire   [31:0] cols_c2_dout;
wire    cols_c2_empty_n;
wire    rows_c_full_n;
wire   [31:0] rows_c_dout;
wire    rows_c_empty_n;
wire    cols_c_full_n;
wire   [31:0] cols_c_dout;
wire    cols_c_empty_n;
wire    rows_c81_full_n;
wire   [31:0] rows_c81_dout;
wire    rows_c81_empty_n;
wire    ImgRgb_Datsrc_rows_V_1_full_n;
wire   [31:0] ImgRgb_Datsrc_rows_V_1_dout;
wire    ImgRgb_Datsrc_rows_V_1_empty_n;
wire    cols_c82_full_n;
wire   [31:0] cols_c82_dout;
wire    cols_c82_empty_n;
wire    ImgRgb_Datsrc_cols_V_1_full_n;
wire   [31:0] ImgRgb_Datsrc_cols_V_1_dout;
wire    ImgRgb_Datsrc_cols_V_1_empty_n;
wire    ImgGry_Datsrc_rows_V_full_n;
wire   [31:0] ImgGry_Datsrc_rows_V_dout;
wire    ImgGry_Datsrc_rows_V_empty_n;
wire    ImgGry_Datsrc_cols_V_full_n;
wire   [31:0] ImgGry_Datsrc_cols_V_dout;
wire    ImgGry_Datsrc_cols_V_empty_n;
wire    ImgGry_Datcop_rows_V_full_n;
wire   [8:0] ImgGry_Datcop_rows_V_dout;
wire    ImgGry_Datcop_rows_V_empty_n;
wire    ImgGry_Datcop_cols_V_full_n;
wire   [9:0] ImgGry_Datcop_cols_V_dout;
wire    ImgGry_Datcop_cols_V_empty_n;
wire    ImgGry_Threh_sp_rows_full_n;
wire   [8:0] ImgGry_Threh_sp_rows_dout;
wire    ImgGry_Threh_sp_rows_empty_n;
wire    ImgGry_Threh_sp_cols_full_n;
wire   [9:0] ImgGry_Threh_sp_cols_dout;
wire    ImgGry_Threh_sp_cols_empty_n;
wire    ImgGry_Threh_cz_rows_full_n;
wire   [8:0] ImgGry_Threh_cz_rows_dout;
wire    ImgGry_Threh_cz_rows_empty_n;
wire    ImgGry_Threh_cz_cols_full_n;
wire   [9:0] ImgGry_Threh_cz_cols_dout;
wire    ImgGry_Threh_cz_cols_empty_n;
wire    ImgGry_Ovlaycz_rows_s_full_n;
wire   [8:0] ImgGry_Ovlaycz_rows_s_dout;
wire    ImgGry_Ovlaycz_rows_s_empty_n;
wire    ImgGry_Ovlaycz_cols_s_full_n;
wire   [9:0] ImgGry_Ovlaycz_cols_s_dout;
wire    ImgGry_Ovlaycz_cols_s_empty_n;
wire    ImgRgb_Datsrc_data_s_full_n;
wire   [7:0] ImgRgb_Datsrc_data_s_dout;
wire    ImgRgb_Datsrc_data_s_empty_n;
wire    ImgRgb_Datsrc_data_s_1_full_n;
wire   [7:0] ImgRgb_Datsrc_data_s_1_dout;
wire    ImgRgb_Datsrc_data_s_1_empty_n;
wire    ImgRgb_Datsrc_data_s_2_full_n;
wire   [7:0] ImgRgb_Datsrc_data_s_2_dout;
wire    ImgRgb_Datsrc_data_s_2_empty_n;
wire    ImgRgb_Datsrc_rows_V_full_n;
wire   [31:0] ImgRgb_Datsrc_rows_V_dout;
wire    ImgRgb_Datsrc_rows_V_empty_n;
wire    ImgRgb_Datsrc_cols_V_full_n;
wire   [31:0] ImgRgb_Datsrc_cols_V_dout;
wire    ImgRgb_Datsrc_cols_V_empty_n;
wire    ImgGry_Datsrc_data_s_full_n;
wire   [7:0] ImgGry_Datsrc_data_s_dout;
wire    ImgGry_Datsrc_data_s_empty_n;
wire    ImgGry_Datsrc_a_data_full_n;
wire   [7:0] ImgGry_Datsrc_a_data_dout;
wire    ImgGry_Datsrc_a_data_empty_n;
wire    ImgGry_Datcop_data_s_full_n;
wire   [7:0] ImgGry_Datcop_data_s_dout;
wire    ImgGry_Datcop_data_s_empty_n;
wire    ImgGry_Datcop_a_data_full_n;
wire   [7:0] ImgGry_Datcop_a_data_dout;
wire    ImgGry_Datcop_a_data_empty_n;
wire    ImgGry_Datcop_b_data_full_n;
wire   [7:0] ImgGry_Datcop_b_data_dout;
wire    ImgGry_Datcop_b_data_empty_n;
wire    ImgGry_Sobcop_cz_dat_full_n;
wire   [7:0] ImgGry_Sobcop_cz_dat_dout;
wire    ImgGry_Sobcop_cz_dat_empty_n;
wire    ImgGry_Sobcop_sp_dat_full_n;
wire   [7:0] ImgGry_Sobcop_sp_dat_dout;
wire    ImgGry_Sobcop_sp_dat_empty_n;
wire    ImgGry_Threh_sp_data_full_n;
wire   [7:0] ImgGry_Threh_sp_data_dout;
wire    ImgGry_Threh_sp_data_empty_n;
wire    ImgGry_Threh_cz_data_full_n;
wire   [7:0] ImgGry_Threh_cz_data_dout;
wire    ImgGry_Threh_cz_data_empty_n;
wire    ImgGry_Copfilt_data_s_full_n;
wire   [7:0] ImgGry_Copfilt_data_s_dout;
wire    ImgGry_Copfilt_data_s_empty_n;
wire    ImgGry_Ovlaycz_data_s_full_n;
wire   [7:0] ImgGry_Ovlaycz_data_s_dout;
wire    ImgGry_Ovlaycz_data_s_empty_n;
wire    ImgGry_Ovlaycz_a_dat_full_n;
wire   [7:0] ImgGry_Ovlaycz_a_dat_dout;
wire    ImgGry_Ovlaycz_a_dat_empty_n;
wire    ImgGry_Ovlaycz_b_dat_full_n;
wire   [7:0] ImgGry_Ovlaycz_b_dat_dout;
wire    ImgGry_Ovlaycz_b_dat_empty_n;
wire    ImgGry_DatCopXs_data_full_n;
wire   [7:0] ImgGry_DatCopXs_data_dout;
wire    ImgGry_DatCopXs_data_empty_n;
wire    ImgGry_OvlyFiltcz_da_full_n;
wire   [7:0] ImgGry_OvlyFiltcz_da_dout;
wire    ImgGry_OvlyFiltcz_da_empty_n;
wire    ImgGry_OvlySumcz_dat_full_n;
wire   [7:0] ImgGry_OvlySumcz_dat_dout;
wire    ImgGry_OvlySumcz_dat_empty_n;
wire   [0:0] start_for_TOP_fuct_entry226_U0_din;
wire    start_for_TOP_fuct_entry226_U0_full_n;
wire   [0:0] start_for_TOP_fuct_entry226_U0_dout;
wire    start_for_TOP_fuct_entry226_U0_empty_n;
wire   [0:0] start_for_Block_TOP_fuct_memin_U0_din;
wire    start_for_Block_TOP_fuct_memin_U0_full_n;
wire   [0:0] start_for_Block_TOP_fuct_memin_U0_dout;
wire    start_for_Block_TOP_fuct_memin_U0_empty_n;
wire    Loop_memset_SobOvlyI_U0_start_full_n;
wire    Loop_memset_SobOvlyI_U0_start_write;
wire   [0:0] start_for_CopImage220_U0_din;
wire    start_for_CopImage220_U0_full_n;
wire   [0:0] start_for_CopImage220_U0_dout;
wire    start_for_CopImage220_U0_empty_n;
wire   [0:0] start_for_Duplicate221_U0_din;
wire    start_for_Duplicate221_U0_full_n;
wire   [0:0] start_for_Duplicate221_U0_dout;
wire    start_for_Duplicate221_U0_empty_n;
wire   [0:0] start_for_Threshold222_U0_din;
wire    start_for_Threshold222_U0_full_n;
wire   [0:0] start_for_Threshold222_U0_dout;
wire    start_for_Threshold222_U0_empty_n;
wire   [0:0] start_for_Threshold_U0_din;
wire    start_for_Threshold_U0_full_n;
wire   [0:0] start_for_Threshold_U0_dout;
wire    start_for_Threshold_U0_empty_n;
wire    Loop_memset_XsOvImSt_U0_start_full_n;
wire    Loop_memset_XsOvImSt_U0_start_write;
wire   [0:0] start_for_CvtColor_U0_din;
wire    start_for_CvtColor_U0_full_n;
wire   [0:0] start_for_CvtColor_U0_dout;
wire    start_for_CvtColor_U0_empty_n;
wire   [0:0] start_for_Duplicate219_U0_din;
wire    start_for_Duplicate219_U0_full_n;
wire   [0:0] start_for_Duplicate219_U0_dout;
wire    start_for_Duplicate219_U0_empty_n;
wire    Duplicate219_U0_start_full_n;
wire    Duplicate219_U0_start_write;
wire    CopImage220_U0_start_full_n;
wire    CopImage220_U0_start_write;
wire   [0:0] start_for_Sobel_U0_din;
wire    start_for_Sobel_U0_full_n;
wire   [0:0] start_for_Sobel_U0_dout;
wire    start_for_Sobel_U0_empty_n;
wire   [0:0] start_for_Sobel_1_U0_din;
wire    start_for_Sobel_1_U0_full_n;
wire   [0:0] start_for_Sobel_1_U0_dout;
wire    start_for_Sobel_1_U0_empty_n;
wire    Sobel_U0_start_full_n;
wire    Sobel_U0_start_write;
wire    Sobel_1_U0_start_full_n;
wire    Sobel_1_U0_start_write;
wire   [0:0] start_for_filtrel_kernel_U0_din;
wire    start_for_filtrel_kernel_U0_full_n;
wire   [0:0] start_for_filtrel_kernel_U0_dout;
wire    start_for_filtrel_kernel_U0_empty_n;
wire    Threshold_U0_start_full_n;
wire    Threshold_U0_start_write;
wire    filtrel_kernel_U0_start_full_n;
wire    filtrel_kernel_U0_start_write;
wire   [0:0] start_for_Duplicate_U0_din;
wire    start_for_Duplicate_U0_full_n;
wire   [0:0] start_for_Duplicate_U0_dout;
wire    start_for_Duplicate_U0_empty_n;
wire   [0:0] start_for_CopImage224_U0_din;
wire    start_for_CopImage224_U0_full_n;
wire   [0:0] start_for_CopImage224_U0_dout;
wire    start_for_CopImage224_U0_empty_n;
wire   [0:0] start_for_filtrel_kernelXS_U0_din;
wire    start_for_filtrel_kernelXS_U0_full_n;
wire   [0:0] start_for_filtrel_kernelXS_U0_dout;
wire    start_for_filtrel_kernelXS_U0_empty_n;
wire    filtrel_kernelXS_U0_start_full_n;
wire    filtrel_kernelXS_U0_start_write;
wire   [0:0] start_for_SeekPoint_U0_din;
wire    start_for_SeekPoint_U0_full_n;
wire   [0:0] start_for_SeekPoint_U0_dout;
wire    start_for_SeekPoint_U0_empty_n;
wire    SeekPoint_U0_start_full_n;
wire    SeekPoint_U0_start_write;

TOP_fuct_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
TOP_fuct_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .rows(rows),
    .cols(cols)
);

TOP_fuct_SobOvlyIAem #(
    .DataWidth( 1 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
SobOvlyIma_Strt_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_memset_SobOvlyI_U0_SobOvlyIma_Strt_address0),
    .i_ce0(Loop_memset_SobOvlyI_U0_SobOvlyIma_Strt_ce0),
    .i_we0(Loop_memset_SobOvlyI_U0_SobOvlyIma_Strt_we0),
    .i_d0(Loop_memset_SobOvlyI_U0_SobOvlyIma_Strt_d0),
    .i_q0(SobOvlyIma_Strt_i_q0),
    .i_address1(1'd0),
    .i_ce1(1'b0),
    .i_q1(SobOvlyIma_Strt_i_q1),
    .t_address0(OvlayImage223_U0_StartLoc_address0),
    .t_ce0(OvlayImage223_U0_StartLoc_ce0),
    .t_we0(1'b0),
    .t_d0(1'd0),
    .t_q0(SobOvlyIma_Strt_t_q0),
    .t_address1(OvlayImage223_U0_StartLoc_address1),
    .t_ce1(OvlayImage223_U0_StartLoc_ce1),
    .t_q1(SobOvlyIma_Strt_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(SobOvlyIma_Strt_i_full_n),
    .i_write(Loop_memset_SobOvlyI_U0_ap_done),
    .t_empty_n(SobOvlyIma_Strt_t_empty_n),
    .t_read(OvlayImage223_U0_ap_ready)
);

TOP_fuct_SobOvlyIAem #(
    .DataWidth( 1 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
XsOvImStrtLoc_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_memset_XsOvImSt_U0_XsOvImStrtLoc_address0),
    .i_ce0(Loop_memset_XsOvImSt_U0_XsOvImStrtLoc_ce0),
    .i_we0(Loop_memset_XsOvImSt_U0_XsOvImStrtLoc_we0),
    .i_d0(Loop_memset_XsOvImSt_U0_XsOvImStrtLoc_d0),
    .i_q0(XsOvImStrtLoc_i_q0),
    .i_address1(1'd0),
    .i_ce1(1'b0),
    .i_q1(XsOvImStrtLoc_i_q1),
    .t_address0(OvlayImage225_U0_StartLoc_address0),
    .t_ce0(OvlayImage225_U0_StartLoc_ce0),
    .t_we0(1'b0),
    .t_d0(1'd0),
    .t_q0(XsOvImStrtLoc_t_q0),
    .t_address1(OvlayImage225_U0_StartLoc_address1),
    .t_ce1(OvlayImage225_U0_StartLoc_ce1),
    .t_q1(XsOvImStrtLoc_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(XsOvImStrtLoc_i_full_n),
    .i_write(Loop_memset_XsOvImSt_U0_ap_done),
    .t_empty_n(XsOvImStrtLoc_t_empty_n),
    .t_read(OvlayImage225_U0_ap_ready)
);

TOP_fuct_K #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
K_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(SeekPoint_U0_K_address0),
    .ce0(SeekPoint_U0_K_ce0),
    .we0(SeekPoint_U0_K_we0),
    .d0(SeekPoint_U0_K_d0),
    .q0(K_q0)
);

TOP_fuct_K #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
B_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(SeekPoint_U0_B_address0),
    .ce0(SeekPoint_U0_B_ce0),
    .we0(SeekPoint_U0_B_we0),
    .d0(SeekPoint_U0_B_d0),
    .q0(B_q0)
);

TOP_fuct_K #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
NumPoint_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(SeekPoint_U0_NumPoint_address0),
    .ce0(SeekPoint_U0_NumPoint_ce0),
    .we0(SeekPoint_U0_NumPoint_we0),
    .d0(SeekPoint_U0_NumPoint_d0),
    .q0(NumPoint_q0)
);

TOP_fuct_entry3 TOP_fuct_entry3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(TOP_fuct_entry3_U0_ap_start),
    .start_full_n(start_for_TOP_fuct_entry226_U0_full_n),
    .ap_done(TOP_fuct_entry3_U0_ap_done),
    .ap_continue(TOP_fuct_entry3_U0_ap_continue),
    .ap_idle(TOP_fuct_entry3_U0_ap_idle),
    .ap_ready(TOP_fuct_entry3_U0_ap_ready),
    .start_out(TOP_fuct_entry3_U0_start_out),
    .start_write(TOP_fuct_entry3_U0_start_write),
    .rows(rows),
    .cols(cols),
    .rows_out_din(TOP_fuct_entry3_U0_rows_out_din),
    .rows_out_full_n(rows_c1_full_n),
    .rows_out_write(TOP_fuct_entry3_U0_rows_out_write),
    .cols_out_din(TOP_fuct_entry3_U0_cols_out_din),
    .cols_out_full_n(cols_c2_full_n),
    .cols_out_write(TOP_fuct_entry3_U0_cols_out_write)
);

TOP_fuct_entry226 TOP_fuct_entry226_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(TOP_fuct_entry226_U0_ap_start),
    .start_full_n(start_for_Block_TOP_fuct_memin_U0_full_n),
    .ap_done(TOP_fuct_entry226_U0_ap_done),
    .ap_continue(TOP_fuct_entry226_U0_ap_continue),
    .ap_idle(TOP_fuct_entry226_U0_ap_idle),
    .ap_ready(TOP_fuct_entry226_U0_ap_ready),
    .start_out(TOP_fuct_entry226_U0_start_out),
    .start_write(TOP_fuct_entry226_U0_start_write),
    .rows_dout(rows_c1_dout),
    .rows_empty_n(rows_c1_empty_n),
    .rows_read(TOP_fuct_entry226_U0_rows_read),
    .cols_dout(cols_c2_dout),
    .cols_empty_n(cols_c2_empty_n),
    .cols_read(TOP_fuct_entry226_U0_cols_read),
    .rows_out_din(TOP_fuct_entry226_U0_rows_out_din),
    .rows_out_full_n(rows_c_full_n),
    .rows_out_write(TOP_fuct_entry226_U0_rows_out_write),
    .cols_out_din(TOP_fuct_entry226_U0_cols_out_din),
    .cols_out_full_n(cols_c_full_n),
    .cols_out_write(TOP_fuct_entry226_U0_cols_out_write)
);

Loop_memset_SobOvlyI Loop_memset_SobOvlyI_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_memset_SobOvlyI_U0_ap_start),
    .ap_done(Loop_memset_SobOvlyI_U0_ap_done),
    .ap_continue(Loop_memset_SobOvlyI_U0_ap_continue),
    .ap_idle(Loop_memset_SobOvlyI_U0_ap_idle),
    .ap_ready(Loop_memset_SobOvlyI_U0_ap_ready),
    .SobOvlyIma_Strt_address0(Loop_memset_SobOvlyI_U0_SobOvlyIma_Strt_address0),
    .SobOvlyIma_Strt_ce0(Loop_memset_SobOvlyI_U0_SobOvlyIma_Strt_ce0),
    .SobOvlyIma_Strt_we0(Loop_memset_SobOvlyI_U0_SobOvlyIma_Strt_we0),
    .SobOvlyIma_Strt_d0(Loop_memset_SobOvlyI_U0_SobOvlyIma_Strt_d0)
);

Block_TOP_fuct_memin Block_TOP_fuct_memin_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_TOP_fuct_memin_U0_ap_start),
    .start_full_n(Block_TOP_fuct_memin_U0_start_full_n),
    .ap_done(Block_TOP_fuct_memin_U0_ap_done),
    .ap_continue(Block_TOP_fuct_memin_U0_ap_continue),
    .ap_idle(Block_TOP_fuct_memin_U0_ap_idle),
    .ap_ready(Block_TOP_fuct_memin_U0_ap_ready),
    .start_out(Block_TOP_fuct_memin_U0_start_out),
    .start_write(Block_TOP_fuct_memin_U0_start_write),
    .rows_dout(rows_c_dout),
    .rows_empty_n(rows_c_empty_n),
    .rows_read(Block_TOP_fuct_memin_U0_rows_read),
    .cols_dout(cols_c_dout),
    .cols_empty_n(cols_c_empty_n),
    .cols_read(Block_TOP_fuct_memin_U0_cols_read),
    .rows_out_din(Block_TOP_fuct_memin_U0_rows_out_din),
    .rows_out_full_n(rows_c81_full_n),
    .rows_out_write(Block_TOP_fuct_memin_U0_rows_out_write),
    .ImgRgb_Datsrc_rows_V_out_din(Block_TOP_fuct_memin_U0_ImgRgb_Datsrc_rows_V_out_din),
    .ImgRgb_Datsrc_rows_V_out_full_n(ImgRgb_Datsrc_rows_V_1_full_n),
    .ImgRgb_Datsrc_rows_V_out_write(Block_TOP_fuct_memin_U0_ImgRgb_Datsrc_rows_V_out_write),
    .cols_out_din(Block_TOP_fuct_memin_U0_cols_out_din),
    .cols_out_full_n(cols_c82_full_n),
    .cols_out_write(Block_TOP_fuct_memin_U0_cols_out_write),
    .ImgRgb_Datsrc_cols_V_out_din(Block_TOP_fuct_memin_U0_ImgRgb_Datsrc_cols_V_out_din),
    .ImgRgb_Datsrc_cols_V_out_full_n(ImgRgb_Datsrc_cols_V_1_full_n),
    .ImgRgb_Datsrc_cols_V_out_write(Block_TOP_fuct_memin_U0_ImgRgb_Datsrc_cols_V_out_write),
    .ImgGry_Datsrc_rows_V_out_din(Block_TOP_fuct_memin_U0_ImgGry_Datsrc_rows_V_out_din),
    .ImgGry_Datsrc_rows_V_out_full_n(ImgGry_Datsrc_rows_V_full_n),
    .ImgGry_Datsrc_rows_V_out_write(Block_TOP_fuct_memin_U0_ImgGry_Datsrc_rows_V_out_write),
    .ImgGry_Datsrc_cols_V_out_din(Block_TOP_fuct_memin_U0_ImgGry_Datsrc_cols_V_out_din),
    .ImgGry_Datsrc_cols_V_out_full_n(ImgGry_Datsrc_cols_V_full_n),
    .ImgGry_Datsrc_cols_V_out_write(Block_TOP_fuct_memin_U0_ImgGry_Datsrc_cols_V_out_write),
    .ImgGry_Datcop_rows_V_out_din(Block_TOP_fuct_memin_U0_ImgGry_Datcop_rows_V_out_din),
    .ImgGry_Datcop_rows_V_out_full_n(ImgGry_Datcop_rows_V_full_n),
    .ImgGry_Datcop_rows_V_out_write(Block_TOP_fuct_memin_U0_ImgGry_Datcop_rows_V_out_write),
    .ImgGry_Datcop_cols_V_out_din(Block_TOP_fuct_memin_U0_ImgGry_Datcop_cols_V_out_din),
    .ImgGry_Datcop_cols_V_out_full_n(ImgGry_Datcop_cols_V_full_n),
    .ImgGry_Datcop_cols_V_out_write(Block_TOP_fuct_memin_U0_ImgGry_Datcop_cols_V_out_write),
    .ImgGry_Threh_sp_rows_V_out_din(Block_TOP_fuct_memin_U0_ImgGry_Threh_sp_rows_V_out_din),
    .ImgGry_Threh_sp_rows_V_out_full_n(ImgGry_Threh_sp_rows_full_n),
    .ImgGry_Threh_sp_rows_V_out_write(Block_TOP_fuct_memin_U0_ImgGry_Threh_sp_rows_V_out_write),
    .ImgGry_Threh_sp_cols_V_out_din(Block_TOP_fuct_memin_U0_ImgGry_Threh_sp_cols_V_out_din),
    .ImgGry_Threh_sp_cols_V_out_full_n(ImgGry_Threh_sp_cols_full_n),
    .ImgGry_Threh_sp_cols_V_out_write(Block_TOP_fuct_memin_U0_ImgGry_Threh_sp_cols_V_out_write),
    .ImgGry_Threh_cz_rows_V_out_din(Block_TOP_fuct_memin_U0_ImgGry_Threh_cz_rows_V_out_din),
    .ImgGry_Threh_cz_rows_V_out_full_n(ImgGry_Threh_cz_rows_full_n),
    .ImgGry_Threh_cz_rows_V_out_write(Block_TOP_fuct_memin_U0_ImgGry_Threh_cz_rows_V_out_write),
    .ImgGry_Threh_cz_cols_V_out_din(Block_TOP_fuct_memin_U0_ImgGry_Threh_cz_cols_V_out_din),
    .ImgGry_Threh_cz_cols_V_out_full_n(ImgGry_Threh_cz_cols_full_n),
    .ImgGry_Threh_cz_cols_V_out_write(Block_TOP_fuct_memin_U0_ImgGry_Threh_cz_cols_V_out_write),
    .ImgGry_Ovlaycz_rows_V_out_din(Block_TOP_fuct_memin_U0_ImgGry_Ovlaycz_rows_V_out_din),
    .ImgGry_Ovlaycz_rows_V_out_full_n(ImgGry_Ovlaycz_rows_s_full_n),
    .ImgGry_Ovlaycz_rows_V_out_write(Block_TOP_fuct_memin_U0_ImgGry_Ovlaycz_rows_V_out_write),
    .ImgGry_Ovlaycz_cols_V_out_din(Block_TOP_fuct_memin_U0_ImgGry_Ovlaycz_cols_V_out_din),
    .ImgGry_Ovlaycz_cols_V_out_full_n(ImgGry_Ovlaycz_cols_s_full_n),
    .ImgGry_Ovlaycz_cols_V_out_write(Block_TOP_fuct_memin_U0_ImgGry_Ovlaycz_cols_V_out_write)
);

Loop_memset_XsOvImSt Loop_memset_XsOvImSt_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_memset_XsOvImSt_U0_ap_start),
    .ap_done(Loop_memset_XsOvImSt_U0_ap_done),
    .ap_continue(Loop_memset_XsOvImSt_U0_ap_continue),
    .ap_idle(Loop_memset_XsOvImSt_U0_ap_idle),
    .ap_ready(Loop_memset_XsOvImSt_U0_ap_ready),
    .XsOvImStrtLoc_address0(Loop_memset_XsOvImSt_U0_XsOvImStrtLoc_address0),
    .XsOvImStrtLoc_ce0(Loop_memset_XsOvImSt_U0_XsOvImStrtLoc_ce0),
    .XsOvImStrtLoc_we0(Loop_memset_XsOvImSt_U0_XsOvImStrtLoc_we0),
    .XsOvImStrtLoc_d0(Loop_memset_XsOvImSt_U0_XsOvImStrtLoc_d0)
);

AXIvideo2Mat AXIvideo2Mat_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2Mat_U0_ap_start),
    .start_full_n(start_for_CvtColor_U0_full_n),
    .ap_done(AXIvideo2Mat_U0_ap_done),
    .ap_continue(AXIvideo2Mat_U0_ap_continue),
    .ap_idle(AXIvideo2Mat_U0_ap_idle),
    .ap_ready(AXIvideo2Mat_U0_ap_ready),
    .start_out(AXIvideo2Mat_U0_start_out),
    .start_write(AXIvideo2Mat_U0_start_write),
    .INPUT_STREAM_TDATA(INPUT_STREAM_TDATA),
    .INPUT_STREAM_TVALID(INPUT_STREAM_TVALID),
    .INPUT_STREAM_TREADY(AXIvideo2Mat_U0_INPUT_STREAM_TREADY),
    .INPUT_STREAM_TKEEP(INPUT_STREAM_TKEEP),
    .INPUT_STREAM_TSTRB(INPUT_STREAM_TSTRB),
    .INPUT_STREAM_TUSER(INPUT_STREAM_TUSER),
    .INPUT_STREAM_TLAST(INPUT_STREAM_TLAST),
    .INPUT_STREAM_TID(INPUT_STREAM_TID),
    .INPUT_STREAM_TDEST(INPUT_STREAM_TDEST),
    .img_rows_V_dout(ImgRgb_Datsrc_rows_V_1_dout),
    .img_rows_V_empty_n(ImgRgb_Datsrc_rows_V_1_empty_n),
    .img_rows_V_read(AXIvideo2Mat_U0_img_rows_V_read),
    .img_cols_V_dout(ImgRgb_Datsrc_cols_V_1_dout),
    .img_cols_V_empty_n(ImgRgb_Datsrc_cols_V_1_empty_n),
    .img_cols_V_read(AXIvideo2Mat_U0_img_cols_V_read),
    .img_data_stream_0_V_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .img_data_stream_0_V_full_n(ImgRgb_Datsrc_data_s_full_n),
    .img_data_stream_0_V_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .img_data_stream_1_V_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .img_data_stream_1_V_full_n(ImgRgb_Datsrc_data_s_1_full_n),
    .img_data_stream_1_V_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .img_data_stream_2_V_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .img_data_stream_2_V_full_n(ImgRgb_Datsrc_data_s_2_full_n),
    .img_data_stream_2_V_write(AXIvideo2Mat_U0_img_data_stream_2_V_write),
    .img_rows_V_out_din(AXIvideo2Mat_U0_img_rows_V_out_din),
    .img_rows_V_out_full_n(ImgRgb_Datsrc_rows_V_full_n),
    .img_rows_V_out_write(AXIvideo2Mat_U0_img_rows_V_out_write),
    .img_cols_V_out_din(AXIvideo2Mat_U0_img_cols_V_out_din),
    .img_cols_V_out_full_n(ImgRgb_Datsrc_cols_V_full_n),
    .img_cols_V_out_write(AXIvideo2Mat_U0_img_cols_V_out_write)
);

CvtColor CvtColor_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(CvtColor_U0_ap_start),
    .start_full_n(start_for_Duplicate219_U0_full_n),
    .ap_done(CvtColor_U0_ap_done),
    .ap_continue(CvtColor_U0_ap_continue),
    .ap_idle(CvtColor_U0_ap_idle),
    .ap_ready(CvtColor_U0_ap_ready),
    .start_out(CvtColor_U0_start_out),
    .start_write(CvtColor_U0_start_write),
    .p_src_rows_V_dout(ImgRgb_Datsrc_rows_V_dout),
    .p_src_rows_V_empty_n(ImgRgb_Datsrc_rows_V_empty_n),
    .p_src_rows_V_read(CvtColor_U0_p_src_rows_V_read),
    .p_src_cols_V_dout(ImgRgb_Datsrc_cols_V_dout),
    .p_src_cols_V_empty_n(ImgRgb_Datsrc_cols_V_empty_n),
    .p_src_cols_V_read(CvtColor_U0_p_src_cols_V_read),
    .p_src_data_stream_0_V_dout(ImgRgb_Datsrc_data_s_dout),
    .p_src_data_stream_0_V_empty_n(ImgRgb_Datsrc_data_s_empty_n),
    .p_src_data_stream_0_V_read(CvtColor_U0_p_src_data_stream_0_V_read),
    .p_src_data_stream_1_V_dout(ImgRgb_Datsrc_data_s_1_dout),
    .p_src_data_stream_1_V_empty_n(ImgRgb_Datsrc_data_s_1_empty_n),
    .p_src_data_stream_1_V_read(CvtColor_U0_p_src_data_stream_1_V_read),
    .p_src_data_stream_2_V_dout(ImgRgb_Datsrc_data_s_2_dout),
    .p_src_data_stream_2_V_empty_n(ImgRgb_Datsrc_data_s_2_empty_n),
    .p_src_data_stream_2_V_read(CvtColor_U0_p_src_data_stream_2_V_read),
    .p_dst_data_stream_V_din(CvtColor_U0_p_dst_data_stream_V_din),
    .p_dst_data_stream_V_full_n(ImgGry_Datsrc_data_s_full_n),
    .p_dst_data_stream_V_write(CvtColor_U0_p_dst_data_stream_V_write)
);

Duplicate219 Duplicate219_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Duplicate219_U0_ap_start),
    .ap_done(Duplicate219_U0_ap_done),
    .ap_continue(Duplicate219_U0_ap_continue),
    .ap_idle(Duplicate219_U0_ap_idle),
    .ap_ready(Duplicate219_U0_ap_ready),
    .src_rows_V_dout(ImgGry_Datsrc_rows_V_dout),
    .src_rows_V_empty_n(ImgGry_Datsrc_rows_V_empty_n),
    .src_rows_V_read(Duplicate219_U0_src_rows_V_read),
    .src_cols_V_dout(ImgGry_Datsrc_cols_V_dout),
    .src_cols_V_empty_n(ImgGry_Datsrc_cols_V_empty_n),
    .src_cols_V_read(Duplicate219_U0_src_cols_V_read),
    .src_data_stream_V_dout(ImgGry_Datsrc_data_s_dout),
    .src_data_stream_V_empty_n(ImgGry_Datsrc_data_s_empty_n),
    .src_data_stream_V_read(Duplicate219_U0_src_data_stream_V_read),
    .dst1_data_stream_V_din(Duplicate219_U0_dst1_data_stream_V_din),
    .dst1_data_stream_V_full_n(ImgGry_Datsrc_a_data_full_n),
    .dst1_data_stream_V_write(Duplicate219_U0_dst1_data_stream_V_write),
    .dst2_data_stream_V(Duplicate219_U0_dst2_data_stream_V),
    .dst2_data_stream_V_ap_vld(Duplicate219_U0_dst2_data_stream_V_ap_vld)
);

CopImage220 CopImage220_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(CopImage220_U0_ap_start),
    .ap_done(CopImage220_U0_ap_done),
    .ap_continue(CopImage220_U0_ap_continue),
    .ap_idle(CopImage220_U0_ap_idle),
    .ap_ready(CopImage220_U0_ap_ready),
    .src_data_stream_V_dout(ImgGry_Datsrc_a_data_dout),
    .src_data_stream_V_empty_n(ImgGry_Datsrc_a_data_empty_n),
    .src_data_stream_V_read(CopImage220_U0_src_data_stream_V_read),
    .dst_data_stream_V_din(CopImage220_U0_dst_data_stream_V_din),
    .dst_data_stream_V_full_n(ImgGry_Datcop_data_s_full_n),
    .dst_data_stream_V_write(CopImage220_U0_dst_data_stream_V_write),
    .HEIGHT_dout(rows_c81_dout),
    .HEIGHT_empty_n(rows_c81_empty_n),
    .HEIGHT_read(CopImage220_U0_HEIGHT_read),
    .WIDTH_dout(cols_c82_dout),
    .WIDTH_empty_n(cols_c82_empty_n),
    .WIDTH_read(CopImage220_U0_WIDTH_read)
);

Duplicate221 Duplicate221_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Duplicate221_U0_ap_start),
    .start_full_n(Duplicate221_U0_start_full_n),
    .ap_done(Duplicate221_U0_ap_done),
    .ap_continue(Duplicate221_U0_ap_continue),
    .ap_idle(Duplicate221_U0_ap_idle),
    .ap_ready(Duplicate221_U0_ap_ready),
    .start_out(Duplicate221_U0_start_out),
    .start_write(Duplicate221_U0_start_write),
    .src_rows_V_dout(ImgGry_Datcop_rows_V_dout),
    .src_rows_V_empty_n(ImgGry_Datcop_rows_V_empty_n),
    .src_rows_V_read(Duplicate221_U0_src_rows_V_read),
    .src_cols_V_dout(ImgGry_Datcop_cols_V_dout),
    .src_cols_V_empty_n(ImgGry_Datcop_cols_V_empty_n),
    .src_cols_V_read(Duplicate221_U0_src_cols_V_read),
    .src_data_stream_V_dout(ImgGry_Datcop_data_s_dout),
    .src_data_stream_V_empty_n(ImgGry_Datcop_data_s_empty_n),
    .src_data_stream_V_read(Duplicate221_U0_src_data_stream_V_read),
    .dst1_data_stream_V_din(Duplicate221_U0_dst1_data_stream_V_din),
    .dst1_data_stream_V_full_n(ImgGry_Datcop_a_data_full_n),
    .dst1_data_stream_V_write(Duplicate221_U0_dst1_data_stream_V_write),
    .dst2_data_stream_V_din(Duplicate221_U0_dst2_data_stream_V_din),
    .dst2_data_stream_V_full_n(ImgGry_Datcop_b_data_full_n),
    .dst2_data_stream_V_write(Duplicate221_U0_dst2_data_stream_V_write)
);

Sobel Sobel_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Sobel_U0_ap_start),
    .ap_done(Sobel_U0_ap_done),
    .ap_continue(Sobel_U0_ap_continue),
    .ap_idle(Sobel_U0_ap_idle),
    .ap_ready(Sobel_U0_ap_ready),
    .p_src_data_stream_V_dout(ImgGry_Datcop_b_data_dout),
    .p_src_data_stream_V_empty_n(ImgGry_Datcop_b_data_empty_n),
    .p_src_data_stream_V_read(Sobel_U0_p_src_data_stream_V_read),
    .p_dst_data_stream_V_din(Sobel_U0_p_dst_data_stream_V_din),
    .p_dst_data_stream_V_full_n(ImgGry_Sobcop_cz_dat_full_n),
    .p_dst_data_stream_V_write(Sobel_U0_p_dst_data_stream_V_write)
);

Sobel_1 Sobel_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Sobel_1_U0_ap_start),
    .ap_done(Sobel_1_U0_ap_done),
    .ap_continue(Sobel_1_U0_ap_continue),
    .ap_idle(Sobel_1_U0_ap_idle),
    .ap_ready(Sobel_1_U0_ap_ready),
    .p_src_data_stream_V_dout(ImgGry_Datcop_a_data_dout),
    .p_src_data_stream_V_empty_n(ImgGry_Datcop_a_data_empty_n),
    .p_src_data_stream_V_read(Sobel_1_U0_p_src_data_stream_V_read),
    .p_dst_data_stream_V_din(Sobel_1_U0_p_dst_data_stream_V_din),
    .p_dst_data_stream_V_full_n(ImgGry_Sobcop_sp_dat_full_n),
    .p_dst_data_stream_V_write(Sobel_1_U0_p_dst_data_stream_V_write)
);

Threshold222 Threshold222_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Threshold222_U0_ap_start),
    .start_full_n(start_for_filtrel_kernel_U0_full_n),
    .ap_done(Threshold222_U0_ap_done),
    .ap_continue(Threshold222_U0_ap_continue),
    .ap_idle(Threshold222_U0_ap_idle),
    .ap_ready(Threshold222_U0_ap_ready),
    .start_out(Threshold222_U0_start_out),
    .start_write(Threshold222_U0_start_write),
    .src_data_stream_V_dout(ImgGry_Sobcop_sp_dat_dout),
    .src_data_stream_V_empty_n(ImgGry_Sobcop_sp_dat_empty_n),
    .src_data_stream_V_read(Threshold222_U0_src_data_stream_V_read),
    .dst_rows_V_dout(ImgGry_Threh_sp_rows_dout),
    .dst_rows_V_empty_n(ImgGry_Threh_sp_rows_empty_n),
    .dst_rows_V_read(Threshold222_U0_dst_rows_V_read),
    .dst_cols_V_dout(ImgGry_Threh_sp_cols_dout),
    .dst_cols_V_empty_n(ImgGry_Threh_sp_cols_empty_n),
    .dst_cols_V_read(Threshold222_U0_dst_cols_V_read),
    .dst_data_stream_V_din(Threshold222_U0_dst_data_stream_V_din),
    .dst_data_stream_V_full_n(ImgGry_Threh_sp_data_full_n),
    .dst_data_stream_V_write(Threshold222_U0_dst_data_stream_V_write)
);

Threshold Threshold_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Threshold_U0_ap_start),
    .ap_done(Threshold_U0_ap_done),
    .ap_continue(Threshold_U0_ap_continue),
    .ap_idle(Threshold_U0_ap_idle),
    .ap_ready(Threshold_U0_ap_ready),
    .src_data_stream_V_dout(ImgGry_Sobcop_cz_dat_dout),
    .src_data_stream_V_empty_n(ImgGry_Sobcop_cz_dat_empty_n),
    .src_data_stream_V_read(Threshold_U0_src_data_stream_V_read),
    .dst_rows_V_dout(ImgGry_Threh_cz_rows_dout),
    .dst_rows_V_empty_n(ImgGry_Threh_cz_rows_empty_n),
    .dst_rows_V_read(Threshold_U0_dst_rows_V_read),
    .dst_cols_V_dout(ImgGry_Threh_cz_cols_dout),
    .dst_cols_V_empty_n(ImgGry_Threh_cz_cols_empty_n),
    .dst_cols_V_read(Threshold_U0_dst_cols_V_read),
    .dst_data_stream_V_din(Threshold_U0_dst_data_stream_V_din),
    .dst_data_stream_V_full_n(ImgGry_Threh_cz_data_full_n),
    .dst_data_stream_V_write(Threshold_U0_dst_data_stream_V_write)
);

filtrel_kernel filtrel_kernel_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(filtrel_kernel_U0_ap_start),
    .ap_done(filtrel_kernel_U0_ap_done),
    .ap_continue(filtrel_kernel_U0_ap_continue),
    .ap_idle(filtrel_kernel_U0_ap_idle),
    .ap_ready(filtrel_kernel_U0_ap_ready),
    .src_data_stream_V_dout(ImgGry_Threh_sp_data_dout),
    .src_data_stream_V_empty_n(ImgGry_Threh_sp_data_empty_n),
    .src_data_stream_V_read(filtrel_kernel_U0_src_data_stream_V_read),
    .dst_data_stream_V_din(filtrel_kernel_U0_dst_data_stream_V_din),
    .dst_data_stream_V_full_n(ImgGry_Copfilt_data_s_full_n),
    .dst_data_stream_V_write(filtrel_kernel_U0_dst_data_stream_V_write)
);

OvlayImage223 OvlayImage223_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(OvlayImage223_U0_ap_start),
    .start_full_n(start_for_Duplicate_U0_full_n),
    .ap_done(OvlayImage223_U0_ap_done),
    .ap_continue(OvlayImage223_U0_ap_continue),
    .ap_idle(OvlayImage223_U0_ap_idle),
    .ap_ready(OvlayImage223_U0_ap_ready),
    .start_out(OvlayImage223_U0_start_out),
    .start_write(OvlayImage223_U0_start_write),
    .src_data_stream_V_dout(ImgGry_Threh_cz_data_dout),
    .src_data_stream_V_empty_n(ImgGry_Threh_cz_data_empty_n),
    .src_data_stream_V_read(OvlayImage223_U0_src_data_stream_V_read),
    .ovlaysrc_data_stream_V_dout(ImgGry_Copfilt_data_s_dout),
    .ovlaysrc_data_stream_V_empty_n(ImgGry_Copfilt_data_s_empty_n),
    .ovlaysrc_data_stream_V_read(OvlayImage223_U0_ovlaysrc_data_stream_V_read),
    .dst_data_stream_V_din(OvlayImage223_U0_dst_data_stream_V_din),
    .dst_data_stream_V_full_n(ImgGry_Ovlaycz_data_s_full_n),
    .dst_data_stream_V_write(OvlayImage223_U0_dst_data_stream_V_write),
    .StartLoc_address0(OvlayImage223_U0_StartLoc_address0),
    .StartLoc_ce0(OvlayImage223_U0_StartLoc_ce0),
    .StartLoc_q0(SobOvlyIma_Strt_t_q0),
    .StartLoc_address1(OvlayImage223_U0_StartLoc_address1),
    .StartLoc_ce1(OvlayImage223_U0_StartLoc_ce1),
    .StartLoc_q1(SobOvlyIma_Strt_t_q1)
);

Duplicate Duplicate_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Duplicate_U0_ap_start),
    .start_full_n(start_for_CopImage224_U0_full_n),
    .ap_done(Duplicate_U0_ap_done),
    .ap_continue(Duplicate_U0_ap_continue),
    .ap_idle(Duplicate_U0_ap_idle),
    .ap_ready(Duplicate_U0_ap_ready),
    .start_out(Duplicate_U0_start_out),
    .start_write(Duplicate_U0_start_write),
    .src_rows_V_dout(ImgGry_Ovlaycz_rows_s_dout),
    .src_rows_V_empty_n(ImgGry_Ovlaycz_rows_s_empty_n),
    .src_rows_V_read(Duplicate_U0_src_rows_V_read),
    .src_cols_V_dout(ImgGry_Ovlaycz_cols_s_dout),
    .src_cols_V_empty_n(ImgGry_Ovlaycz_cols_s_empty_n),
    .src_cols_V_read(Duplicate_U0_src_cols_V_read),
    .src_data_stream_V_dout(ImgGry_Ovlaycz_data_s_dout),
    .src_data_stream_V_empty_n(ImgGry_Ovlaycz_data_s_empty_n),
    .src_data_stream_V_read(Duplicate_U0_src_data_stream_V_read),
    .dst1_data_stream_V_din(Duplicate_U0_dst1_data_stream_V_din),
    .dst1_data_stream_V_full_n(ImgGry_Ovlaycz_a_dat_full_n),
    .dst1_data_stream_V_write(Duplicate_U0_dst1_data_stream_V_write),
    .dst2_data_stream_V_din(Duplicate_U0_dst2_data_stream_V_din),
    .dst2_data_stream_V_full_n(ImgGry_Ovlaycz_b_dat_full_n),
    .dst2_data_stream_V_write(Duplicate_U0_dst2_data_stream_V_write)
);

CopImage224 CopImage224_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(CopImage224_U0_ap_start),
    .start_full_n(start_for_filtrel_kernelXS_U0_full_n),
    .ap_done(CopImage224_U0_ap_done),
    .ap_continue(CopImage224_U0_ap_continue),
    .ap_idle(CopImage224_U0_ap_idle),
    .ap_ready(CopImage224_U0_ap_ready),
    .start_out(CopImage224_U0_start_out),
    .start_write(CopImage224_U0_start_write),
    .src_data_stream_V_dout(ImgGry_Ovlaycz_a_dat_dout),
    .src_data_stream_V_empty_n(ImgGry_Ovlaycz_a_dat_empty_n),
    .src_data_stream_V_read(CopImage224_U0_src_data_stream_V_read),
    .dst_data_stream_V_din(CopImage224_U0_dst_data_stream_V_din),
    .dst_data_stream_V_full_n(ImgGry_DatCopXs_data_full_n),
    .dst_data_stream_V_write(CopImage224_U0_dst_data_stream_V_write)
);

filtrel_kernelXS filtrel_kernelXS_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(filtrel_kernelXS_U0_ap_start),
    .ap_done(filtrel_kernelXS_U0_ap_done),
    .ap_continue(filtrel_kernelXS_U0_ap_continue),
    .ap_idle(filtrel_kernelXS_U0_ap_idle),
    .ap_ready(filtrel_kernelXS_U0_ap_ready),
    .src_data_stream_V_dout(ImgGry_DatCopXs_data_dout),
    .src_data_stream_V_empty_n(ImgGry_DatCopXs_data_empty_n),
    .src_data_stream_V_read(filtrel_kernelXS_U0_src_data_stream_V_read),
    .dst_data_stream_V_din(filtrel_kernelXS_U0_dst_data_stream_V_din),
    .dst_data_stream_V_full_n(ImgGry_OvlyFiltcz_da_full_n),
    .dst_data_stream_V_write(filtrel_kernelXS_U0_dst_data_stream_V_write)
);

OvlayImage225 OvlayImage225_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(OvlayImage225_U0_ap_start),
    .start_full_n(start_for_SeekPoint_U0_full_n),
    .ap_done(OvlayImage225_U0_ap_done),
    .ap_continue(OvlayImage225_U0_ap_continue),
    .ap_idle(OvlayImage225_U0_ap_idle),
    .ap_ready(OvlayImage225_U0_ap_ready),
    .start_out(OvlayImage225_U0_start_out),
    .start_write(OvlayImage225_U0_start_write),
    .src_data_stream_V_dout(ImgGry_Ovlaycz_b_dat_dout),
    .src_data_stream_V_empty_n(ImgGry_Ovlaycz_b_dat_empty_n),
    .src_data_stream_V_read(OvlayImage225_U0_src_data_stream_V_read),
    .ovlaysrc_data_stream_V_dout(ImgGry_OvlyFiltcz_da_dout),
    .ovlaysrc_data_stream_V_empty_n(ImgGry_OvlyFiltcz_da_empty_n),
    .ovlaysrc_data_stream_V_read(OvlayImage225_U0_ovlaysrc_data_stream_V_read),
    .dst_data_stream_V_din(OvlayImage225_U0_dst_data_stream_V_din),
    .dst_data_stream_V_full_n(ImgGry_OvlySumcz_dat_full_n),
    .dst_data_stream_V_write(OvlayImage225_U0_dst_data_stream_V_write),
    .StartLoc_address0(OvlayImage225_U0_StartLoc_address0),
    .StartLoc_ce0(OvlayImage225_U0_StartLoc_ce0),
    .StartLoc_q0(XsOvImStrtLoc_t_q0),
    .StartLoc_address1(OvlayImage225_U0_StartLoc_address1),
    .StartLoc_ce1(OvlayImage225_U0_StartLoc_ce1),
    .StartLoc_q1(XsOvImStrtLoc_t_q1)
);

SeekPoint SeekPoint_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(SeekPoint_U0_ap_start),
    .ap_done(SeekPoint_U0_ap_done),
    .ap_continue(SeekPoint_U0_ap_continue),
    .ap_idle(SeekPoint_U0_ap_idle),
    .ap_ready(SeekPoint_U0_ap_ready),
    .src_data_stream_V_dout(ImgGry_OvlySumcz_dat_dout),
    .src_data_stream_V_empty_n(ImgGry_OvlySumcz_dat_empty_n),
    .src_data_stream_V_read(SeekPoint_U0_src_data_stream_V_read),
    .K_address0(SeekPoint_U0_K_address0),
    .K_ce0(SeekPoint_U0_K_ce0),
    .K_we0(SeekPoint_U0_K_we0),
    .K_d0(SeekPoint_U0_K_d0),
    .K_q0(K_q0),
    .B_address0(SeekPoint_U0_B_address0),
    .B_ce0(SeekPoint_U0_B_ce0),
    .B_we0(SeekPoint_U0_B_we0),
    .B_d0(SeekPoint_U0_B_d0),
    .B_q0(B_q0),
    .NumPoint_address0(SeekPoint_U0_NumPoint_address0),
    .NumPoint_ce0(SeekPoint_U0_NumPoint_ce0),
    .NumPoint_we0(SeekPoint_U0_NumPoint_we0),
    .NumPoint_d0(SeekPoint_U0_NumPoint_d0),
    .NumPoint_q0(NumPoint_q0)
);

fifo_w32_d2_A rows_c1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(TOP_fuct_entry3_U0_rows_out_din),
    .if_full_n(rows_c1_full_n),
    .if_write(TOP_fuct_entry3_U0_rows_out_write),
    .if_dout(rows_c1_dout),
    .if_empty_n(rows_c1_empty_n),
    .if_read(TOP_fuct_entry226_U0_rows_read)
);

fifo_w32_d2_A cols_c2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(TOP_fuct_entry3_U0_cols_out_din),
    .if_full_n(cols_c2_full_n),
    .if_write(TOP_fuct_entry3_U0_cols_out_write),
    .if_dout(cols_c2_dout),
    .if_empty_n(cols_c2_empty_n),
    .if_read(TOP_fuct_entry226_U0_cols_read)
);

fifo_w32_d2_A rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(TOP_fuct_entry226_U0_rows_out_din),
    .if_full_n(rows_c_full_n),
    .if_write(TOP_fuct_entry226_U0_rows_out_write),
    .if_dout(rows_c_dout),
    .if_empty_n(rows_c_empty_n),
    .if_read(Block_TOP_fuct_memin_U0_rows_read)
);

fifo_w32_d2_A cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(TOP_fuct_entry226_U0_cols_out_din),
    .if_full_n(cols_c_full_n),
    .if_write(TOP_fuct_entry226_U0_cols_out_write),
    .if_dout(cols_c_dout),
    .if_empty_n(cols_c_empty_n),
    .if_read(Block_TOP_fuct_memin_U0_cols_read)
);

fifo_w32_d5_A rows_c81_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_TOP_fuct_memin_U0_rows_out_din),
    .if_full_n(rows_c81_full_n),
    .if_write(Block_TOP_fuct_memin_U0_rows_out_write),
    .if_dout(rows_c81_dout),
    .if_empty_n(rows_c81_empty_n),
    .if_read(CopImage220_U0_HEIGHT_read)
);

fifo_w32_d2_A ImgRgb_Datsrc_rows_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_TOP_fuct_memin_U0_ImgRgb_Datsrc_rows_V_out_din),
    .if_full_n(ImgRgb_Datsrc_rows_V_1_full_n),
    .if_write(Block_TOP_fuct_memin_U0_ImgRgb_Datsrc_rows_V_out_write),
    .if_dout(ImgRgb_Datsrc_rows_V_1_dout),
    .if_empty_n(ImgRgb_Datsrc_rows_V_1_empty_n),
    .if_read(AXIvideo2Mat_U0_img_rows_V_read)
);

fifo_w32_d5_A cols_c82_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_TOP_fuct_memin_U0_cols_out_din),
    .if_full_n(cols_c82_full_n),
    .if_write(Block_TOP_fuct_memin_U0_cols_out_write),
    .if_dout(cols_c82_dout),
    .if_empty_n(cols_c82_empty_n),
    .if_read(CopImage220_U0_WIDTH_read)
);

fifo_w32_d2_A ImgRgb_Datsrc_cols_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_TOP_fuct_memin_U0_ImgRgb_Datsrc_cols_V_out_din),
    .if_full_n(ImgRgb_Datsrc_cols_V_1_full_n),
    .if_write(Block_TOP_fuct_memin_U0_ImgRgb_Datsrc_cols_V_out_write),
    .if_dout(ImgRgb_Datsrc_cols_V_1_dout),
    .if_empty_n(ImgRgb_Datsrc_cols_V_1_empty_n),
    .if_read(AXIvideo2Mat_U0_img_cols_V_read)
);

fifo_w32_d4_A ImgGry_Datsrc_rows_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_TOP_fuct_memin_U0_ImgGry_Datsrc_rows_V_out_din),
    .if_full_n(ImgGry_Datsrc_rows_V_full_n),
    .if_write(Block_TOP_fuct_memin_U0_ImgGry_Datsrc_rows_V_out_write),
    .if_dout(ImgGry_Datsrc_rows_V_dout),
    .if_empty_n(ImgGry_Datsrc_rows_V_empty_n),
    .if_read(Duplicate219_U0_src_rows_V_read)
);

fifo_w32_d4_A ImgGry_Datsrc_cols_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_TOP_fuct_memin_U0_ImgGry_Datsrc_cols_V_out_din),
    .if_full_n(ImgGry_Datsrc_cols_V_full_n),
    .if_write(Block_TOP_fuct_memin_U0_ImgGry_Datsrc_cols_V_out_write),
    .if_dout(ImgGry_Datsrc_cols_V_dout),
    .if_empty_n(ImgGry_Datsrc_cols_V_empty_n),
    .if_read(Duplicate219_U0_src_cols_V_read)
);

fifo_w9_d6_A ImgGry_Datcop_rows_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_TOP_fuct_memin_U0_ImgGry_Datcop_rows_V_out_din),
    .if_full_n(ImgGry_Datcop_rows_V_full_n),
    .if_write(Block_TOP_fuct_memin_U0_ImgGry_Datcop_rows_V_out_write),
    .if_dout(ImgGry_Datcop_rows_V_dout),
    .if_empty_n(ImgGry_Datcop_rows_V_empty_n),
    .if_read(Duplicate221_U0_src_rows_V_read)
);

fifo_w10_d6_A ImgGry_Datcop_cols_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_TOP_fuct_memin_U0_ImgGry_Datcop_cols_V_out_din),
    .if_full_n(ImgGry_Datcop_cols_V_full_n),
    .if_write(Block_TOP_fuct_memin_U0_ImgGry_Datcop_cols_V_out_write),
    .if_dout(ImgGry_Datcop_cols_V_dout),
    .if_empty_n(ImgGry_Datcop_cols_V_empty_n),
    .if_read(Duplicate221_U0_src_cols_V_read)
);

fifo_w9_d8_A ImgGry_Threh_sp_rows_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_TOP_fuct_memin_U0_ImgGry_Threh_sp_rows_V_out_din),
    .if_full_n(ImgGry_Threh_sp_rows_full_n),
    .if_write(Block_TOP_fuct_memin_U0_ImgGry_Threh_sp_rows_V_out_write),
    .if_dout(ImgGry_Threh_sp_rows_dout),
    .if_empty_n(ImgGry_Threh_sp_rows_empty_n),
    .if_read(Threshold222_U0_dst_rows_V_read)
);

fifo_w10_d8_A ImgGry_Threh_sp_cols_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_TOP_fuct_memin_U0_ImgGry_Threh_sp_cols_V_out_din),
    .if_full_n(ImgGry_Threh_sp_cols_full_n),
    .if_write(Block_TOP_fuct_memin_U0_ImgGry_Threh_sp_cols_V_out_write),
    .if_dout(ImgGry_Threh_sp_cols_dout),
    .if_empty_n(ImgGry_Threh_sp_cols_empty_n),
    .if_read(Threshold222_U0_dst_cols_V_read)
);

fifo_w9_d8_A ImgGry_Threh_cz_rows_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_TOP_fuct_memin_U0_ImgGry_Threh_cz_rows_V_out_din),
    .if_full_n(ImgGry_Threh_cz_rows_full_n),
    .if_write(Block_TOP_fuct_memin_U0_ImgGry_Threh_cz_rows_V_out_write),
    .if_dout(ImgGry_Threh_cz_rows_dout),
    .if_empty_n(ImgGry_Threh_cz_rows_empty_n),
    .if_read(Threshold_U0_dst_rows_V_read)
);

fifo_w10_d8_A ImgGry_Threh_cz_cols_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_TOP_fuct_memin_U0_ImgGry_Threh_cz_cols_V_out_din),
    .if_full_n(ImgGry_Threh_cz_cols_full_n),
    .if_write(Block_TOP_fuct_memin_U0_ImgGry_Threh_cz_cols_V_out_write),
    .if_dout(ImgGry_Threh_cz_cols_dout),
    .if_empty_n(ImgGry_Threh_cz_cols_empty_n),
    .if_read(Threshold_U0_dst_cols_V_read)
);

fifo_w9_d11_A ImgGry_Ovlaycz_rows_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_TOP_fuct_memin_U0_ImgGry_Ovlaycz_rows_V_out_din),
    .if_full_n(ImgGry_Ovlaycz_rows_s_full_n),
    .if_write(Block_TOP_fuct_memin_U0_ImgGry_Ovlaycz_rows_V_out_write),
    .if_dout(ImgGry_Ovlaycz_rows_s_dout),
    .if_empty_n(ImgGry_Ovlaycz_rows_s_empty_n),
    .if_read(Duplicate_U0_src_rows_V_read)
);

fifo_w10_d11_A ImgGry_Ovlaycz_cols_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_TOP_fuct_memin_U0_ImgGry_Ovlaycz_cols_V_out_din),
    .if_full_n(ImgGry_Ovlaycz_cols_s_full_n),
    .if_write(Block_TOP_fuct_memin_U0_ImgGry_Ovlaycz_cols_V_out_write),
    .if_dout(ImgGry_Ovlaycz_cols_s_dout),
    .if_empty_n(ImgGry_Ovlaycz_cols_s_empty_n),
    .if_read(Duplicate_U0_src_cols_V_read)
);

fifo_w8_d2_A ImgRgb_Datsrc_data_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .if_full_n(ImgRgb_Datsrc_data_s_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .if_dout(ImgRgb_Datsrc_data_s_dout),
    .if_empty_n(ImgRgb_Datsrc_data_s_empty_n),
    .if_read(CvtColor_U0_p_src_data_stream_0_V_read)
);

fifo_w8_d2_A ImgRgb_Datsrc_data_s_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .if_full_n(ImgRgb_Datsrc_data_s_1_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .if_dout(ImgRgb_Datsrc_data_s_1_dout),
    .if_empty_n(ImgRgb_Datsrc_data_s_1_empty_n),
    .if_read(CvtColor_U0_p_src_data_stream_1_V_read)
);

fifo_w8_d2_A ImgRgb_Datsrc_data_s_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .if_full_n(ImgRgb_Datsrc_data_s_2_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_2_V_write),
    .if_dout(ImgRgb_Datsrc_data_s_2_dout),
    .if_empty_n(ImgRgb_Datsrc_data_s_2_empty_n),
    .if_read(CvtColor_U0_p_src_data_stream_2_V_read)
);

fifo_w32_d2_A ImgRgb_Datsrc_rows_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_rows_V_out_din),
    .if_full_n(ImgRgb_Datsrc_rows_V_full_n),
    .if_write(AXIvideo2Mat_U0_img_rows_V_out_write),
    .if_dout(ImgRgb_Datsrc_rows_V_dout),
    .if_empty_n(ImgRgb_Datsrc_rows_V_empty_n),
    .if_read(CvtColor_U0_p_src_rows_V_read)
);

fifo_w32_d2_A ImgRgb_Datsrc_cols_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_cols_V_out_din),
    .if_full_n(ImgRgb_Datsrc_cols_V_full_n),
    .if_write(AXIvideo2Mat_U0_img_cols_V_out_write),
    .if_dout(ImgRgb_Datsrc_cols_V_dout),
    .if_empty_n(ImgRgb_Datsrc_cols_V_empty_n),
    .if_read(CvtColor_U0_p_src_cols_V_read)
);

fifo_w8_d2_A ImgGry_Datsrc_data_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(CvtColor_U0_p_dst_data_stream_V_din),
    .if_full_n(ImgGry_Datsrc_data_s_full_n),
    .if_write(CvtColor_U0_p_dst_data_stream_V_write),
    .if_dout(ImgGry_Datsrc_data_s_dout),
    .if_empty_n(ImgGry_Datsrc_data_s_empty_n),
    .if_read(Duplicate219_U0_src_data_stream_V_read)
);

fifo_w8_d2_A ImgGry_Datsrc_a_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Duplicate219_U0_dst1_data_stream_V_din),
    .if_full_n(ImgGry_Datsrc_a_data_full_n),
    .if_write(Duplicate219_U0_dst1_data_stream_V_write),
    .if_dout(ImgGry_Datsrc_a_data_dout),
    .if_empty_n(ImgGry_Datsrc_a_data_empty_n),
    .if_read(CopImage220_U0_src_data_stream_V_read)
);

fifo_w8_d2_A ImgGry_Datcop_data_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(CopImage220_U0_dst_data_stream_V_din),
    .if_full_n(ImgGry_Datcop_data_s_full_n),
    .if_write(CopImage220_U0_dst_data_stream_V_write),
    .if_dout(ImgGry_Datcop_data_s_dout),
    .if_empty_n(ImgGry_Datcop_data_s_empty_n),
    .if_read(Duplicate221_U0_src_data_stream_V_read)
);

fifo_w8_d2_A ImgGry_Datcop_a_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Duplicate221_U0_dst1_data_stream_V_din),
    .if_full_n(ImgGry_Datcop_a_data_full_n),
    .if_write(Duplicate221_U0_dst1_data_stream_V_write),
    .if_dout(ImgGry_Datcop_a_data_dout),
    .if_empty_n(ImgGry_Datcop_a_data_empty_n),
    .if_read(Sobel_1_U0_p_src_data_stream_V_read)
);

fifo_w8_d2_A ImgGry_Datcop_b_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Duplicate221_U0_dst2_data_stream_V_din),
    .if_full_n(ImgGry_Datcop_b_data_full_n),
    .if_write(Duplicate221_U0_dst2_data_stream_V_write),
    .if_dout(ImgGry_Datcop_b_data_dout),
    .if_empty_n(ImgGry_Datcop_b_data_empty_n),
    .if_read(Sobel_U0_p_src_data_stream_V_read)
);

fifo_w8_d2_A ImgGry_Sobcop_cz_dat_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_U0_p_dst_data_stream_V_din),
    .if_full_n(ImgGry_Sobcop_cz_dat_full_n),
    .if_write(Sobel_U0_p_dst_data_stream_V_write),
    .if_dout(ImgGry_Sobcop_cz_dat_dout),
    .if_empty_n(ImgGry_Sobcop_cz_dat_empty_n),
    .if_read(Threshold_U0_src_data_stream_V_read)
);

fifo_w8_d2_A ImgGry_Sobcop_sp_dat_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_1_U0_p_dst_data_stream_V_din),
    .if_full_n(ImgGry_Sobcop_sp_dat_full_n),
    .if_write(Sobel_1_U0_p_dst_data_stream_V_write),
    .if_dout(ImgGry_Sobcop_sp_dat_dout),
    .if_empty_n(ImgGry_Sobcop_sp_dat_empty_n),
    .if_read(Threshold222_U0_src_data_stream_V_read)
);

fifo_w8_d2_A ImgGry_Threh_sp_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Threshold222_U0_dst_data_stream_V_din),
    .if_full_n(ImgGry_Threh_sp_data_full_n),
    .if_write(Threshold222_U0_dst_data_stream_V_write),
    .if_dout(ImgGry_Threh_sp_data_dout),
    .if_empty_n(ImgGry_Threh_sp_data_empty_n),
    .if_read(filtrel_kernel_U0_src_data_stream_V_read)
);

fifo_w8_d2_A ImgGry_Threh_cz_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Threshold_U0_dst_data_stream_V_din),
    .if_full_n(ImgGry_Threh_cz_data_full_n),
    .if_write(Threshold_U0_dst_data_stream_V_write),
    .if_dout(ImgGry_Threh_cz_data_dout),
    .if_empty_n(ImgGry_Threh_cz_data_empty_n),
    .if_read(OvlayImage223_U0_src_data_stream_V_read)
);

fifo_w8_d2_A ImgGry_Copfilt_data_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(filtrel_kernel_U0_dst_data_stream_V_din),
    .if_full_n(ImgGry_Copfilt_data_s_full_n),
    .if_write(filtrel_kernel_U0_dst_data_stream_V_write),
    .if_dout(ImgGry_Copfilt_data_s_dout),
    .if_empty_n(ImgGry_Copfilt_data_s_empty_n),
    .if_read(OvlayImage223_U0_ovlaysrc_data_stream_V_read)
);

fifo_w8_d2_A ImgGry_Ovlaycz_data_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(OvlayImage223_U0_dst_data_stream_V_din),
    .if_full_n(ImgGry_Ovlaycz_data_s_full_n),
    .if_write(OvlayImage223_U0_dst_data_stream_V_write),
    .if_dout(ImgGry_Ovlaycz_data_s_dout),
    .if_empty_n(ImgGry_Ovlaycz_data_s_empty_n),
    .if_read(Duplicate_U0_src_data_stream_V_read)
);

fifo_w8_d2_A ImgGry_Ovlaycz_a_dat_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Duplicate_U0_dst1_data_stream_V_din),
    .if_full_n(ImgGry_Ovlaycz_a_dat_full_n),
    .if_write(Duplicate_U0_dst1_data_stream_V_write),
    .if_dout(ImgGry_Ovlaycz_a_dat_dout),
    .if_empty_n(ImgGry_Ovlaycz_a_dat_empty_n),
    .if_read(CopImage224_U0_src_data_stream_V_read)
);

fifo_w8_d2_A ImgGry_Ovlaycz_b_dat_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Duplicate_U0_dst2_data_stream_V_din),
    .if_full_n(ImgGry_Ovlaycz_b_dat_full_n),
    .if_write(Duplicate_U0_dst2_data_stream_V_write),
    .if_dout(ImgGry_Ovlaycz_b_dat_dout),
    .if_empty_n(ImgGry_Ovlaycz_b_dat_empty_n),
    .if_read(OvlayImage225_U0_src_data_stream_V_read)
);

fifo_w8_d2_A ImgGry_DatCopXs_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(CopImage224_U0_dst_data_stream_V_din),
    .if_full_n(ImgGry_DatCopXs_data_full_n),
    .if_write(CopImage224_U0_dst_data_stream_V_write),
    .if_dout(ImgGry_DatCopXs_data_dout),
    .if_empty_n(ImgGry_DatCopXs_data_empty_n),
    .if_read(filtrel_kernelXS_U0_src_data_stream_V_read)
);

fifo_w8_d2_A ImgGry_OvlyFiltcz_da_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(filtrel_kernelXS_U0_dst_data_stream_V_din),
    .if_full_n(ImgGry_OvlyFiltcz_da_full_n),
    .if_write(filtrel_kernelXS_U0_dst_data_stream_V_write),
    .if_dout(ImgGry_OvlyFiltcz_da_dout),
    .if_empty_n(ImgGry_OvlyFiltcz_da_empty_n),
    .if_read(OvlayImage225_U0_ovlaysrc_data_stream_V_read)
);

fifo_w8_d2_A ImgGry_OvlySumcz_dat_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(OvlayImage225_U0_dst_data_stream_V_din),
    .if_full_n(ImgGry_OvlySumcz_dat_full_n),
    .if_write(OvlayImage225_U0_dst_data_stream_V_write),
    .if_dout(ImgGry_OvlySumcz_dat_dout),
    .if_empty_n(ImgGry_OvlySumcz_dat_empty_n),
    .if_read(SeekPoint_U0_src_data_stream_V_read)
);

start_for_TOP_fucCeG start_for_TOP_fucCeG_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_TOP_fuct_entry226_U0_din),
    .if_full_n(start_for_TOP_fuct_entry226_U0_full_n),
    .if_write(TOP_fuct_entry3_U0_start_write),
    .if_dout(start_for_TOP_fuct_entry226_U0_dout),
    .if_empty_n(start_for_TOP_fuct_entry226_U0_empty_n),
    .if_read(TOP_fuct_entry226_U0_ap_ready)
);

start_for_Block_TDeQ start_for_Block_TDeQ_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Block_TOP_fuct_memin_U0_din),
    .if_full_n(start_for_Block_TOP_fuct_memin_U0_full_n),
    .if_write(TOP_fuct_entry226_U0_start_write),
    .if_dout(start_for_Block_TOP_fuct_memin_U0_dout),
    .if_empty_n(start_for_Block_TOP_fuct_memin_U0_empty_n),
    .if_read(Block_TOP_fuct_memin_U0_ap_ready)
);

start_for_CopImagEe0 start_for_CopImagEe0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_CopImage220_U0_din),
    .if_full_n(start_for_CopImage220_U0_full_n),
    .if_write(Block_TOP_fuct_memin_U0_start_write),
    .if_dout(start_for_CopImage220_U0_dout),
    .if_empty_n(start_for_CopImage220_U0_empty_n),
    .if_read(CopImage220_U0_ap_ready)
);

start_for_DuplicaFfa start_for_DuplicaFfa_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Duplicate221_U0_din),
    .if_full_n(start_for_Duplicate221_U0_full_n),
    .if_write(Block_TOP_fuct_memin_U0_start_write),
    .if_dout(start_for_Duplicate221_U0_dout),
    .if_empty_n(start_for_Duplicate221_U0_empty_n),
    .if_read(Duplicate221_U0_ap_ready)
);

start_for_ThreshoGfk start_for_ThreshoGfk_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Threshold222_U0_din),
    .if_full_n(start_for_Threshold222_U0_full_n),
    .if_write(Block_TOP_fuct_memin_U0_start_write),
    .if_dout(start_for_Threshold222_U0_dout),
    .if_empty_n(start_for_Threshold222_U0_empty_n),
    .if_read(Threshold222_U0_ap_ready)
);

start_for_ThreshoHfu start_for_ThreshoHfu_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Threshold_U0_din),
    .if_full_n(start_for_Threshold_U0_full_n),
    .if_write(Block_TOP_fuct_memin_U0_start_write),
    .if_dout(start_for_Threshold_U0_dout),
    .if_empty_n(start_for_Threshold_U0_empty_n),
    .if_read(Threshold_U0_ap_ready)
);

start_for_CvtColoIfE start_for_CvtColoIfE_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_CvtColor_U0_din),
    .if_full_n(start_for_CvtColor_U0_full_n),
    .if_write(AXIvideo2Mat_U0_start_write),
    .if_dout(start_for_CvtColor_U0_dout),
    .if_empty_n(start_for_CvtColor_U0_empty_n),
    .if_read(CvtColor_U0_ap_ready)
);

start_for_DuplicaJfO start_for_DuplicaJfO_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Duplicate219_U0_din),
    .if_full_n(start_for_Duplicate219_U0_full_n),
    .if_write(CvtColor_U0_start_write),
    .if_dout(start_for_Duplicate219_U0_dout),
    .if_empty_n(start_for_Duplicate219_U0_empty_n),
    .if_read(Duplicate219_U0_ap_ready)
);

start_for_Sobel_U0 start_for_Sobel_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Sobel_U0_din),
    .if_full_n(start_for_Sobel_U0_full_n),
    .if_write(Duplicate221_U0_start_write),
    .if_dout(start_for_Sobel_U0_dout),
    .if_empty_n(start_for_Sobel_U0_empty_n),
    .if_read(Sobel_U0_ap_ready)
);

start_for_Sobel_1KfY start_for_Sobel_1KfY_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Sobel_1_U0_din),
    .if_full_n(start_for_Sobel_1_U0_full_n),
    .if_write(Duplicate221_U0_start_write),
    .if_dout(start_for_Sobel_1_U0_dout),
    .if_empty_n(start_for_Sobel_1_U0_empty_n),
    .if_read(Sobel_1_U0_ap_ready)
);

start_for_filtrelLf8 start_for_filtrelLf8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_filtrel_kernel_U0_din),
    .if_full_n(start_for_filtrel_kernel_U0_full_n),
    .if_write(Threshold222_U0_start_write),
    .if_dout(start_for_filtrel_kernel_U0_dout),
    .if_empty_n(start_for_filtrel_kernel_U0_empty_n),
    .if_read(filtrel_kernel_U0_ap_ready)
);

start_for_DuplicaMgi start_for_DuplicaMgi_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Duplicate_U0_din),
    .if_full_n(start_for_Duplicate_U0_full_n),
    .if_write(OvlayImage223_U0_start_write),
    .if_dout(start_for_Duplicate_U0_dout),
    .if_empty_n(start_for_Duplicate_U0_empty_n),
    .if_read(Duplicate_U0_ap_ready)
);

start_for_CopImagNgs start_for_CopImagNgs_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_CopImage224_U0_din),
    .if_full_n(start_for_CopImage224_U0_full_n),
    .if_write(Duplicate_U0_start_write),
    .if_dout(start_for_CopImage224_U0_dout),
    .if_empty_n(start_for_CopImage224_U0_empty_n),
    .if_read(CopImage224_U0_ap_ready)
);

start_for_filtrelOgC start_for_filtrelOgC_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_filtrel_kernelXS_U0_din),
    .if_full_n(start_for_filtrel_kernelXS_U0_full_n),
    .if_write(CopImage224_U0_start_write),
    .if_dout(start_for_filtrel_kernelXS_U0_dout),
    .if_empty_n(start_for_filtrel_kernelXS_U0_empty_n),
    .if_read(filtrel_kernelXS_U0_ap_ready)
);

start_for_SeekPoiPgM start_for_SeekPoiPgM_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_SeekPoint_U0_din),
    .if_full_n(start_for_SeekPoint_U0_full_n),
    .if_write(OvlayImage225_U0_start_write),
    .if_dout(start_for_SeekPoint_U0_dout),
    .if_empty_n(start_for_SeekPoint_U0_empty_n),
    .if_read(SeekPoint_U0_ap_ready)
);

assign AXIvideo2Mat_U0_ap_continue = 1'b1;

assign AXIvideo2Mat_U0_ap_start = 1'b1;

assign Block_TOP_fuct_memin_U0_ap_continue = 1'b1;

assign Block_TOP_fuct_memin_U0_ap_start = start_for_Block_TOP_fuct_memin_U0_empty_n;

assign Block_TOP_fuct_memin_U0_start_full_n = (start_for_Threshold_U0_full_n & start_for_Threshold222_U0_full_n & start_for_Duplicate221_U0_full_n & start_for_CopImage220_U0_full_n);

assign CopImage220_U0_ap_continue = 1'b1;

assign CopImage220_U0_ap_start = start_for_CopImage220_U0_empty_n;

assign CopImage220_U0_start_full_n = 1'b1;

assign CopImage220_U0_start_write = 1'b0;

assign CopImage224_U0_ap_continue = 1'b1;

assign CopImage224_U0_ap_start = start_for_CopImage224_U0_empty_n;

assign CvtColor_U0_ap_continue = 1'b1;

assign CvtColor_U0_ap_start = start_for_CvtColor_U0_empty_n;

assign Duplicate219_U0_ap_continue = 1'b1;

assign Duplicate219_U0_ap_start = start_for_Duplicate219_U0_empty_n;

assign Duplicate219_U0_start_full_n = 1'b1;

assign Duplicate219_U0_start_write = 1'b0;

assign Duplicate221_U0_ap_continue = 1'b1;

assign Duplicate221_U0_ap_start = start_for_Duplicate221_U0_empty_n;

assign Duplicate221_U0_start_full_n = (start_for_Sobel_U0_full_n & start_for_Sobel_1_U0_full_n);

assign Duplicate_U0_ap_continue = 1'b1;

assign Duplicate_U0_ap_start = start_for_Duplicate_U0_empty_n;

assign INPUT_STREAM_TREADY = AXIvideo2Mat_U0_INPUT_STREAM_TREADY;

assign Loop_memset_SobOvlyI_U0_SobOvlyIma_Strt_full_n = SobOvlyIma_Strt_i_full_n;

assign Loop_memset_SobOvlyI_U0_ap_continue = SobOvlyIma_Strt_i_full_n;

assign Loop_memset_SobOvlyI_U0_ap_start = 1'b1;

assign Loop_memset_SobOvlyI_U0_start_full_n = 1'b1;

assign Loop_memset_SobOvlyI_U0_start_write = 1'b0;

assign Loop_memset_XsOvImSt_U0_XsOvImStrtLoc_full_n = XsOvImStrtLoc_i_full_n;

assign Loop_memset_XsOvImSt_U0_ap_continue = XsOvImStrtLoc_i_full_n;

assign Loop_memset_XsOvImSt_U0_ap_start = 1'b1;

assign Loop_memset_XsOvImSt_U0_start_full_n = 1'b1;

assign Loop_memset_XsOvImSt_U0_start_write = 1'b0;

assign OvlayImage223_U0_ap_continue = 1'b1;

assign OvlayImage223_U0_ap_start = SobOvlyIma_Strt_t_empty_n;

assign OvlayImage225_U0_ap_continue = 1'b1;

assign OvlayImage225_U0_ap_start = XsOvImStrtLoc_t_empty_n;

assign SeekPoint_U0_ap_continue = 1'b1;

assign SeekPoint_U0_ap_start = start_for_SeekPoint_U0_empty_n;

assign SeekPoint_U0_start_full_n = 1'b1;

assign SeekPoint_U0_start_write = 1'b0;

assign SobOvlyIma_Strt_t_d1 = 1'd0;

assign SobOvlyIma_Strt_t_we1 = 1'b0;

assign Sobel_1_U0_ap_continue = 1'b1;

assign Sobel_1_U0_ap_start = start_for_Sobel_1_U0_empty_n;

assign Sobel_1_U0_start_full_n = 1'b1;

assign Sobel_1_U0_start_write = 1'b0;

assign Sobel_U0_ap_continue = 1'b1;

assign Sobel_U0_ap_start = start_for_Sobel_U0_empty_n;

assign Sobel_U0_start_full_n = 1'b1;

assign Sobel_U0_start_write = 1'b0;

assign TOP_fuct_entry226_U0_ap_continue = 1'b1;

assign TOP_fuct_entry226_U0_ap_start = start_for_TOP_fuct_entry226_U0_empty_n;

assign TOP_fuct_entry3_U0_ap_continue = 1'b1;

assign TOP_fuct_entry3_U0_ap_start = 1'b1;

assign Threshold222_U0_ap_continue = 1'b1;

assign Threshold222_U0_ap_start = start_for_Threshold222_U0_empty_n;

assign Threshold_U0_ap_continue = 1'b1;

assign Threshold_U0_ap_start = start_for_Threshold_U0_empty_n;

assign Threshold_U0_start_full_n = 1'b1;

assign Threshold_U0_start_write = 1'b0;

assign XsOvImStrtLoc_t_d1 = 1'd0;

assign XsOvImStrtLoc_t_we1 = 1'b0;

assign ap_channel_done_SobOvlyIma_Strt = Loop_memset_SobOvlyI_U0_ap_done;

assign ap_channel_done_XsOvImStrtLoc = Loop_memset_XsOvImSt_U0_ap_done;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign filtrel_kernelXS_U0_ap_continue = 1'b1;

assign filtrel_kernelXS_U0_ap_start = start_for_filtrel_kernelXS_U0_empty_n;

assign filtrel_kernelXS_U0_start_full_n = 1'b1;

assign filtrel_kernelXS_U0_start_write = 1'b0;

assign filtrel_kernel_U0_ap_continue = 1'b1;

assign filtrel_kernel_U0_ap_start = start_for_filtrel_kernel_U0_empty_n;

assign filtrel_kernel_U0_start_full_n = 1'b1;

assign filtrel_kernel_U0_start_write = 1'b0;

assign start_for_Block_TOP_fuct_memin_U0_din = 1'b1;

assign start_for_CopImage220_U0_din = 1'b1;

assign start_for_CopImage224_U0_din = 1'b1;

assign start_for_CvtColor_U0_din = 1'b1;

assign start_for_Duplicate219_U0_din = 1'b1;

assign start_for_Duplicate221_U0_din = 1'b1;

assign start_for_Duplicate_U0_din = 1'b1;

assign start_for_SeekPoint_U0_din = 1'b1;

assign start_for_Sobel_1_U0_din = 1'b1;

assign start_for_Sobel_U0_din = 1'b1;

assign start_for_TOP_fuct_entry226_U0_din = 1'b1;

assign start_for_Threshold222_U0_din = 1'b1;

assign start_for_Threshold_U0_din = 1'b1;

assign start_for_filtrel_kernelXS_U0_din = 1'b1;

assign start_for_filtrel_kernel_U0_din = 1'b1;

endmodule //TOP_fuct
