// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "filtrel_kernel.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic filtrel_kernel::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic filtrel_kernel::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<11> filtrel_kernel::ap_ST_fsm_state1 = "1";
const sc_lv<11> filtrel_kernel::ap_ST_fsm_state2 = "10";
const sc_lv<11> filtrel_kernel::ap_ST_fsm_state3 = "100";
const sc_lv<11> filtrel_kernel::ap_ST_fsm_state4 = "1000";
const sc_lv<11> filtrel_kernel::ap_ST_fsm_state5 = "10000";
const sc_lv<11> filtrel_kernel::ap_ST_fsm_state6 = "100000";
const sc_lv<11> filtrel_kernel::ap_ST_fsm_state7 = "1000000";
const sc_lv<11> filtrel_kernel::ap_ST_fsm_state8 = "10000000";
const sc_lv<11> filtrel_kernel::ap_ST_fsm_state9 = "100000000";
const sc_lv<11> filtrel_kernel::ap_ST_fsm_state10 = "1000000000";
const sc_lv<11> filtrel_kernel::ap_ST_fsm_state11 = "10000000000";
const sc_lv<32> filtrel_kernel::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> filtrel_kernel::ap_const_lv32_3 = "11";
const sc_lv<1> filtrel_kernel::ap_const_lv1_0 = "0";
const sc_lv<32> filtrel_kernel::ap_const_lv32_A = "1010";
const sc_lv<1> filtrel_kernel::ap_const_lv1_1 = "1";
const sc_lv<32> filtrel_kernel::ap_const_lv32_1 = "1";
const sc_lv<32> filtrel_kernel::ap_const_lv32_2 = "10";
const sc_lv<32> filtrel_kernel::ap_const_lv32_4 = "100";
const sc_lv<32> filtrel_kernel::ap_const_lv32_5 = "101";
const sc_lv<32> filtrel_kernel::ap_const_lv32_6 = "110";
const sc_lv<32> filtrel_kernel::ap_const_lv32_8 = "1000";
const sc_lv<32> filtrel_kernel::ap_const_lv32_9 = "1001";
const sc_lv<5> filtrel_kernel::ap_const_lv5_0 = "00000";
const sc_lv<4> filtrel_kernel::ap_const_lv4_0 = "0000";
const sc_lv<12> filtrel_kernel::ap_const_lv12_0 = "000000000000";
const sc_lv<9> filtrel_kernel::ap_const_lv9_0 = "000000000";
const sc_lv<32> filtrel_kernel::ap_const_lv32_7 = "111";
const sc_lv<18> filtrel_kernel::ap_const_lv18_0 = "000000000000000000";
const sc_lv<8> filtrel_kernel::ap_const_lv8_FF = "11111111";
const sc_lv<8> filtrel_kernel::ap_const_lv8_0 = "00000000";
const sc_lv<5> filtrel_kernel::ap_const_lv5_12 = "10010";
const sc_lv<5> filtrel_kernel::ap_const_lv5_1 = "1";
const sc_lv<12> filtrel_kernel::ap_const_lv12_122 = "100100010";
const sc_lv<4> filtrel_kernel::ap_const_lv4_A = "1010";
const sc_lv<4> filtrel_kernel::ap_const_lv4_1 = "1";
const sc_lv<9> filtrel_kernel::ap_const_lv9_122 = "100100010";
const sc_lv<9> filtrel_kernel::ap_const_lv9_1 = "1";
const sc_lv<5> filtrel_kernel::ap_const_lv5_1D = "11101";
const sc_lv<3> filtrel_kernel::ap_const_lv3_0 = "000";
const sc_lv<32> filtrel_kernel::ap_const_lv32_1F = "11111";
const sc_lv<28> filtrel_kernel::ap_const_lv28_0 = "0000000000000000000000000000";
const sc_lv<18> filtrel_kernel::ap_const_lv18_334 = "1100110100";
const sc_lv<32> filtrel_kernel::ap_const_lv32_D = "1101";
const sc_lv<32> filtrel_kernel::ap_const_lv32_11 = "10001";
const sc_lv<13> filtrel_kernel::ap_const_lv13_122 = "100100010";
const bool filtrel_kernel::ap_const_boolean_1 = true;

filtrel_kernel::filtrel_kernel(sc_module_name name) : sc_module(name), mVcdFile(0) {
    line_buf1_U = new filtrel_kernel_likbM("line_buf1_U");
    line_buf1_U->clk(ap_clk);
    line_buf1_U->reset(ap_rst);
    line_buf1_U->address0(line_buf1_address0);
    line_buf1_U->ce0(line_buf1_ce0);
    line_buf1_U->we0(line_buf1_we0);
    line_buf1_U->d0(src_data_stream_V_dout);
    line_buf1_U->q0(line_buf1_q0);
    Line_Flag2_U = new filtrel_kernel_LilbW("Line_Flag2_U");
    Line_Flag2_U->clk(ap_clk);
    Line_Flag2_U->reset(ap_rst);
    Line_Flag2_U->address0(Line_Flag2_address0);
    Line_Flag2_U->ce0(Line_Flag2_ce0);
    Line_Flag2_U->we0(Line_Flag2_we0);
    Line_Flag2_U->d0(Line_Flag2_d0);
    Line_Flag2_U->q0(Line_Flag2_q0);
    TOP_fuct_mul_mul_mb6_U99 = new TOP_fuct_mul_mul_mb6<1,1,10,13,13>("TOP_fuct_mul_mul_mb6_U99");
    TOP_fuct_mul_mul_mb6_U99->din0(tmp_18_fu_588_p0);
    TOP_fuct_mul_mul_mb6_U99->din1(tmp_18_fu_588_p1);
    TOP_fuct_mul_mul_mb6_U99->dout(tmp_18_fu_588_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Line_Flag2_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( Line_Flag2_addr_reg_631 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_s_fu_413_p1 );
    sensitive << ( tmp_20_fu_583_p1 );

    SC_METHOD(thread_Line_Flag2_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_Line_Flag2_d0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_Line_Flag2_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond6_fu_401_p2 );
    sensitive << ( tmp_19_reg_659 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_23_fu_514_p2 );
    sensitive << ( icmp_fu_537_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state11);
    sensitive << ( dst_data_stream_V_full_n );
    sensitive << ( Line_Flag2_q0 );

    SC_METHOD(thread_ap_block_state4);
    sensitive << ( src_data_stream_V_empty_n );
    sensitive << ( exitcond7_fu_374_p2 );

    SC_METHOD(thread_ap_condition_260);
    sensitive << ( dst_data_stream_V_full_n );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( Line_Flag2_q0 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond8_fu_344_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_flag_be_phi_fu_302_p4);
    sensitive << ( tmp_19_reg_659 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_23_fu_514_p2 );
    sensitive << ( icmp_fu_537_p2 );
    sensitive << ( flag_be_reg_297 );

    SC_METHOD(thread_ap_phi_mux_temp_1_be_phi_fu_289_p4);
    sensitive << ( tmp_19_reg_659 );
    sensitive << ( temp_1_reg_262 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_23_fu_514_p2 );
    sensitive << ( icmp_fu_537_p2 );
    sensitive << ( temp_3_fu_520_p2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond8_fu_344_p2 );

    SC_METHOD(thread_count_2_fu_350_p2);
    sensitive << ( count_reg_172 );

    SC_METHOD(thread_dst_data_stream_V_blk_n);
    sensitive << ( dst_data_stream_V_full_n );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( Line_Flag2_q0 );

    SC_METHOD(thread_dst_data_stream_V_din);
    sensitive << ( Line_Flag2_q0 );
    sensitive << ( ap_condition_260 );

    SC_METHOD(thread_dst_data_stream_V_write);
    sensitive << ( dst_data_stream_V_full_n );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( Line_Flag2_q0 );

    SC_METHOD(thread_exitcond3_fu_555_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( xi2_reg_322 );

    SC_METHOD(thread_exitcond4_fu_362_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( yi_reg_183 );

    SC_METHOD(thread_exitcond6_fu_401_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i_reg_217 );

    SC_METHOD(thread_exitcond7_fu_374_p2);
    sensitive << ( src_data_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond7_fu_374_p2 );
    sensitive << ( xi_reg_206 );

    SC_METHOD(thread_exitcond8_fu_344_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( count_reg_172 );

    SC_METHOD(thread_exitcond_fu_543_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( yi1_reg_311 );

    SC_METHOD(thread_i_2_fu_407_p2);
    sensitive << ( i_reg_217 );

    SC_METHOD(thread_icmp_fu_537_p2);
    sensitive << ( tmp_19_reg_659 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_23_fu_514_p2 );
    sensitive << ( tmp_13_fu_527_p4 );

    SC_METHOD(thread_j_2_fu_460_p2);
    sensitive << ( j_reg_251 );

    SC_METHOD(thread_k_2_fu_480_p2);
    sensitive << ( k_reg_274 );

    SC_METHOD(thread_k_cast8_cast_fu_470_p1);
    sensitive << ( k_reg_274 );

    SC_METHOD(thread_line_buf1_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( p_sum1_cast_fu_396_p1 );
    sensitive << ( p_sum_cast_fu_509_p1 );

    SC_METHOD(thread_line_buf1_ce0);
    sensitive << ( src_data_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond7_fu_374_p2 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_line_buf1_we0);
    sensitive << ( src_data_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond7_fu_374_p2 );

    SC_METHOD(thread_next_mul2_fu_567_p2);
    sensitive << ( phi_mul2_reg_333 );

    SC_METHOD(thread_next_mul_fu_356_p2);
    sensitive << ( phi_mul_reg_194 );

    SC_METHOD(thread_or_cond7_fu_454_p2);
    sensitive << ( tmp_16_fu_442_p2 );
    sensitive << ( tmp_17_fu_448_p2 );

    SC_METHOD(thread_p_shl9_cast_cast_fu_438_p1);
    sensitive << ( p_shl9_fu_430_p3 );

    SC_METHOD(thread_p_shl9_fu_430_p3);
    sensitive << ( i_reg_217 );

    SC_METHOD(thread_p_shl_cast_fu_426_p1);
    sensitive << ( p_shl_fu_418_p3 );

    SC_METHOD(thread_p_shl_fu_418_p3);
    sensitive << ( i_reg_217 );

    SC_METHOD(thread_p_sum1_cast_fu_396_p1);
    sensitive << ( p_sum1_fu_390_p2 );

    SC_METHOD(thread_p_sum1_fu_390_p2);
    sensitive << ( phi_mul_reg_194 );
    sensitive << ( tmp_54_cast_fu_386_p1 );

    SC_METHOD(thread_p_sum_cast_fu_509_p1);
    sensitive << ( p_sum_fu_504_p2 );

    SC_METHOD(thread_p_sum_fu_504_p2);
    sensitive << ( tmp_18_reg_654 );
    sensitive << ( tmp_61_cast_fu_500_p1 );

    SC_METHOD(thread_src_data_stream_V_blk_n);
    sensitive << ( src_data_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond7_fu_374_p2 );

    SC_METHOD(thread_src_data_stream_V_read);
    sensitive << ( src_data_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond7_fu_374_p2 );

    SC_METHOD(thread_temp_3_fu_520_p2);
    sensitive << ( temp_1_reg_262 );

    SC_METHOD(thread_tmp1_cast_fu_491_p1);
    sensitive << ( tmp1_fu_486_p2 );

    SC_METHOD(thread_tmp1_fu_486_p2);
    sensitive << ( p_shl9_cast_cast_reg_641 );
    sensitive << ( k_cast8_cast_fu_470_p1 );

    SC_METHOD(thread_tmp_12_fu_573_p4);
    sensitive << ( phi_mul2_reg_333 );

    SC_METHOD(thread_tmp_13_fu_527_p4);
    sensitive << ( temp_1_reg_262 );

    SC_METHOD(thread_tmp_16_fu_442_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( j_reg_251 );

    SC_METHOD(thread_tmp_17_fu_448_p2);
    sensitive << ( flag_reg_240 );

    SC_METHOD(thread_tmp_18_fu_588_p0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_tmp_18_fu_588_p1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( j_reg_251 );

    SC_METHOD(thread_tmp_19_fu_474_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( k_reg_274 );

    SC_METHOD(thread_tmp_20_fu_583_p1);
    sensitive << ( tmp_12_fu_573_p4 );

    SC_METHOD(thread_tmp_22_fu_495_p2);
    sensitive << ( p_shl_cast_reg_636 );
    sensitive << ( tmp1_cast_fu_491_p1 );

    SC_METHOD(thread_tmp_23_fu_514_p2);
    sensitive << ( tmp_19_reg_659 );
    sensitive << ( line_buf1_q0 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_tmp_54_cast_fu_386_p1);
    sensitive << ( xi_reg_206 );

    SC_METHOD(thread_tmp_61_cast_fu_500_p1);
    sensitive << ( tmp_22_fu_495_p2 );

    SC_METHOD(thread_tmp_s_fu_413_p1);
    sensitive << ( i_reg_217 );

    SC_METHOD(thread_xi_3_fu_380_p2);
    sensitive << ( xi_reg_206 );

    SC_METHOD(thread_xi_4_fu_561_p2);
    sensitive << ( xi2_reg_322 );

    SC_METHOD(thread_yi_3_fu_368_p2);
    sensitive << ( yi_reg_183 );

    SC_METHOD(thread_yi_4_fu_549_p2);
    sensitive << ( yi1_reg_311 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( src_data_stream_V_empty_n );
    sensitive << ( dst_data_stream_V_full_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond7_fu_374_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( Line_Flag2_q0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond6_fu_401_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( or_cond7_fu_454_p2 );
    sensitive << ( tmp_19_reg_659 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( exitcond3_fu_555_p2 );
    sensitive << ( exitcond_fu_543_p2 );
    sensitive << ( exitcond8_fu_344_p2 );
    sensitive << ( exitcond4_fu_362_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_23_fu_514_p2 );
    sensitive << ( icmp_fu_537_p2 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "filtrel_kernel_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, src_data_stream_V_dout, "(port)src_data_stream_V_dout");
    sc_trace(mVcdFile, src_data_stream_V_empty_n, "(port)src_data_stream_V_empty_n");
    sc_trace(mVcdFile, src_data_stream_V_read, "(port)src_data_stream_V_read");
    sc_trace(mVcdFile, dst_data_stream_V_din, "(port)dst_data_stream_V_din");
    sc_trace(mVcdFile, dst_data_stream_V_full_n, "(port)dst_data_stream_V_full_n");
    sc_trace(mVcdFile, dst_data_stream_V_write, "(port)dst_data_stream_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, src_data_stream_V_blk_n, "src_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, exitcond7_fu_374_p2, "exitcond7_fu_374_p2");
    sc_trace(mVcdFile, dst_data_stream_V_blk_n, "dst_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, Line_Flag2_q0, "Line_Flag2_q0");
    sc_trace(mVcdFile, count_2_fu_350_p2, "count_2_fu_350_p2");
    sc_trace(mVcdFile, count_2_reg_597, "count_2_reg_597");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, next_mul_fu_356_p2, "next_mul_fu_356_p2");
    sc_trace(mVcdFile, next_mul_reg_602, "next_mul_reg_602");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, yi_3_fu_368_p2, "yi_3_fu_368_p2");
    sc_trace(mVcdFile, yi_3_reg_610, "yi_3_reg_610");
    sc_trace(mVcdFile, xi_3_fu_380_p2, "xi_3_fu_380_p2");
    sc_trace(mVcdFile, ap_block_state4, "ap_block_state4");
    sc_trace(mVcdFile, i_2_fu_407_p2, "i_2_fu_407_p2");
    sc_trace(mVcdFile, i_2_reg_626, "i_2_reg_626");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, Line_Flag2_addr_reg_631, "Line_Flag2_addr_reg_631");
    sc_trace(mVcdFile, exitcond6_fu_401_p2, "exitcond6_fu_401_p2");
    sc_trace(mVcdFile, p_shl_cast_fu_426_p1, "p_shl_cast_fu_426_p1");
    sc_trace(mVcdFile, p_shl_cast_reg_636, "p_shl_cast_reg_636");
    sc_trace(mVcdFile, p_shl9_cast_cast_fu_438_p1, "p_shl9_cast_cast_fu_438_p1");
    sc_trace(mVcdFile, p_shl9_cast_cast_reg_641, "p_shl9_cast_cast_reg_641");
    sc_trace(mVcdFile, j_2_fu_460_p2, "j_2_fu_460_p2");
    sc_trace(mVcdFile, j_2_reg_649, "j_2_reg_649");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_18_fu_588_p2, "tmp_18_fu_588_p2");
    sc_trace(mVcdFile, tmp_18_reg_654, "tmp_18_reg_654");
    sc_trace(mVcdFile, or_cond7_fu_454_p2, "or_cond7_fu_454_p2");
    sc_trace(mVcdFile, tmp_19_fu_474_p2, "tmp_19_fu_474_p2");
    sc_trace(mVcdFile, tmp_19_reg_659, "tmp_19_reg_659");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, k_2_fu_480_p2, "k_2_fu_480_p2");
    sc_trace(mVcdFile, k_2_reg_663, "k_2_reg_663");
    sc_trace(mVcdFile, yi_4_fu_549_p2, "yi_4_fu_549_p2");
    sc_trace(mVcdFile, yi_4_reg_682, "yi_4_reg_682");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, xi_4_fu_561_p2, "xi_4_fu_561_p2");
    sc_trace(mVcdFile, xi_4_reg_690, "xi_4_reg_690");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, next_mul2_fu_567_p2, "next_mul2_fu_567_p2");
    sc_trace(mVcdFile, next_mul2_reg_695, "next_mul2_reg_695");
    sc_trace(mVcdFile, exitcond3_fu_555_p2, "exitcond3_fu_555_p2");
    sc_trace(mVcdFile, line_buf1_address0, "line_buf1_address0");
    sc_trace(mVcdFile, line_buf1_ce0, "line_buf1_ce0");
    sc_trace(mVcdFile, line_buf1_we0, "line_buf1_we0");
    sc_trace(mVcdFile, line_buf1_q0, "line_buf1_q0");
    sc_trace(mVcdFile, Line_Flag2_address0, "Line_Flag2_address0");
    sc_trace(mVcdFile, Line_Flag2_ce0, "Line_Flag2_ce0");
    sc_trace(mVcdFile, Line_Flag2_we0, "Line_Flag2_we0");
    sc_trace(mVcdFile, Line_Flag2_d0, "Line_Flag2_d0");
    sc_trace(mVcdFile, count_reg_172, "count_reg_172");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, exitcond_fu_543_p2, "exitcond_fu_543_p2");
    sc_trace(mVcdFile, yi_reg_183, "yi_reg_183");
    sc_trace(mVcdFile, exitcond8_fu_344_p2, "exitcond8_fu_344_p2");
    sc_trace(mVcdFile, phi_mul_reg_194, "phi_mul_reg_194");
    sc_trace(mVcdFile, xi_reg_206, "xi_reg_206");
    sc_trace(mVcdFile, exitcond4_fu_362_p2, "exitcond4_fu_362_p2");
    sc_trace(mVcdFile, i_reg_217, "i_reg_217");
    sc_trace(mVcdFile, temp_reg_228, "temp_reg_228");
    sc_trace(mVcdFile, temp_1_reg_262, "temp_1_reg_262");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, tmp_23_fu_514_p2, "tmp_23_fu_514_p2");
    sc_trace(mVcdFile, icmp_fu_537_p2, "icmp_fu_537_p2");
    sc_trace(mVcdFile, flag_reg_240, "flag_reg_240");
    sc_trace(mVcdFile, ap_phi_mux_flag_be_phi_fu_302_p4, "ap_phi_mux_flag_be_phi_fu_302_p4");
    sc_trace(mVcdFile, j_reg_251, "j_reg_251");
    sc_trace(mVcdFile, ap_phi_mux_temp_1_be_phi_fu_289_p4, "ap_phi_mux_temp_1_be_phi_fu_289_p4");
    sc_trace(mVcdFile, k_reg_274, "k_reg_274");
    sc_trace(mVcdFile, temp_3_fu_520_p2, "temp_3_fu_520_p2");
    sc_trace(mVcdFile, flag_be_reg_297, "flag_be_reg_297");
    sc_trace(mVcdFile, yi1_reg_311, "yi1_reg_311");
    sc_trace(mVcdFile, xi2_reg_322, "xi2_reg_322");
    sc_trace(mVcdFile, ap_block_state11, "ap_block_state11");
    sc_trace(mVcdFile, phi_mul2_reg_333, "phi_mul2_reg_333");
    sc_trace(mVcdFile, p_sum1_cast_fu_396_p1, "p_sum1_cast_fu_396_p1");
    sc_trace(mVcdFile, tmp_s_fu_413_p1, "tmp_s_fu_413_p1");
    sc_trace(mVcdFile, p_sum_cast_fu_509_p1, "p_sum_cast_fu_509_p1");
    sc_trace(mVcdFile, tmp_20_fu_583_p1, "tmp_20_fu_583_p1");
    sc_trace(mVcdFile, tmp_54_cast_fu_386_p1, "tmp_54_cast_fu_386_p1");
    sc_trace(mVcdFile, p_sum1_fu_390_p2, "p_sum1_fu_390_p2");
    sc_trace(mVcdFile, p_shl_fu_418_p3, "p_shl_fu_418_p3");
    sc_trace(mVcdFile, p_shl9_fu_430_p3, "p_shl9_fu_430_p3");
    sc_trace(mVcdFile, tmp_16_fu_442_p2, "tmp_16_fu_442_p2");
    sc_trace(mVcdFile, tmp_17_fu_448_p2, "tmp_17_fu_448_p2");
    sc_trace(mVcdFile, k_cast8_cast_fu_470_p1, "k_cast8_cast_fu_470_p1");
    sc_trace(mVcdFile, tmp1_fu_486_p2, "tmp1_fu_486_p2");
    sc_trace(mVcdFile, tmp1_cast_fu_491_p1, "tmp1_cast_fu_491_p1");
    sc_trace(mVcdFile, tmp_22_fu_495_p2, "tmp_22_fu_495_p2");
    sc_trace(mVcdFile, tmp_61_cast_fu_500_p1, "tmp_61_cast_fu_500_p1");
    sc_trace(mVcdFile, p_sum_fu_504_p2, "p_sum_fu_504_p2");
    sc_trace(mVcdFile, tmp_13_fu_527_p4, "tmp_13_fu_527_p4");
    sc_trace(mVcdFile, tmp_12_fu_573_p4, "tmp_12_fu_573_p4");
    sc_trace(mVcdFile, tmp_18_fu_588_p0, "tmp_18_fu_588_p0");
    sc_trace(mVcdFile, tmp_18_fu_588_p1, "tmp_18_fu_588_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_condition_260, "ap_condition_260");
#endif

    }
}

filtrel_kernel::~filtrel_kernel() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete line_buf1_U;
    delete Line_Flag2_U;
    delete TOP_fuct_mul_mul_mb6_U99;
}

void filtrel_kernel::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, exitcond8_fu_344_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_543_p2.read()))) {
        count_reg_172 = count_2_reg_597.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        count_reg_172 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_474_p2.read()))) {
        flag_be_reg_297 = ap_const_lv1_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_fu_514_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_fu_537_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_19_reg_659.read()))) {
        flag_be_reg_297 = ap_const_lv1_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         ((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_fu_514_p2.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_1, icmp_fu_537_p2.read())) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_reg_659.read())))) {
        flag_reg_240 = ap_phi_mux_flag_be_phi_fu_302_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_401_p2.read()))) {
        flag_reg_240 = ap_const_lv1_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond4_fu_362_p2.read()))) {
        i_reg_217 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_454_p2.read()))) {
        i_reg_217 = i_2_reg_626.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         ((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_fu_514_p2.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_1, icmp_fu_537_p2.read())) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_reg_659.read())))) {
        j_reg_251 = j_2_reg_649.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_401_p2.read()))) {
        j_reg_251 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         ((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_19_reg_659.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_537_p2.read())) || 
          (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_19_reg_659.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, tmp_23_fu_514_p2.read()))))) {
        k_reg_274 = k_2_reg_663.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, or_cond7_fu_454_p2.read()))) {
        k_reg_274 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_543_p2.read()))) {
        phi_mul2_reg_333 = ap_const_lv18_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
                !((esl_seteq<1,1,1>(ap_const_lv1_0, Line_Flag2_q0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())) || (esl_seteq<1,1,1>(Line_Flag2_q0.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read()))))) {
        phi_mul2_reg_333 = next_mul2_reg_695.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_344_p2.read()))) {
        phi_mul_reg_194 = ap_const_lv12_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                !(esl_seteq<1,1,1>(exitcond7_fu_374_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read())) && 
                esl_seteq<1,1,1>(exitcond7_fu_374_p2.read(), ap_const_lv1_1))) {
        phi_mul_reg_194 = next_mul_reg_602.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         ((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_19_reg_659.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_537_p2.read())) || 
          (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_19_reg_659.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_0, tmp_23_fu_514_p2.read()))))) {
        temp_1_reg_262 = ap_phi_mux_temp_1_be_phi_fu_289_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, or_cond7_fu_454_p2.read()))) {
        temp_1_reg_262 = temp_reg_228.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         ((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_fu_514_p2.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_1, icmp_fu_537_p2.read())) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_reg_659.read())))) {
        temp_reg_228 = temp_1_reg_262.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_401_p2.read()))) {
        temp_reg_228 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_543_p2.read()))) {
        xi2_reg_322 = ap_const_lv9_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
                !((esl_seteq<1,1,1>(ap_const_lv1_0, Line_Flag2_q0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())) || (esl_seteq<1,1,1>(Line_Flag2_q0.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read()))))) {
        xi2_reg_322 = xi_4_reg_690.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_362_p2.read()))) {
        xi_reg_206 = ap_const_lv9_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(exitcond7_fu_374_p2.read(), ap_const_lv1_0) && 
                !(esl_seteq<1,1,1>(exitcond7_fu_374_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read())))) {
        xi_reg_206 = xi_3_fu_380_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond6_fu_401_p2.read()))) {
        yi1_reg_311 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, exitcond3_fu_555_p2.read()))) {
        yi1_reg_311 = yi_4_reg_682.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_344_p2.read()))) {
        yi_reg_183 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                !(esl_seteq<1,1,1>(exitcond7_fu_374_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read())) && 
                esl_seteq<1,1,1>(exitcond7_fu_374_p2.read(), ap_const_lv1_1))) {
        yi_reg_183 = yi_3_reg_610.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_401_p2.read()))) {
        Line_Flag2_addr_reg_631 =  (sc_lv<5>) (tmp_s_fu_413_p1.read());
        p_shl9_cast_cast_reg_641 = p_shl9_cast_cast_fu_438_p1.read();
        p_shl_cast_reg_636 = p_shl_cast_fu_426_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        count_2_reg_597 = count_2_fu_350_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_2_reg_626 = i_2_fu_407_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j_2_reg_649 = j_2_fu_460_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        k_2_reg_663 = k_2_fu_480_p2.read();
        tmp_19_reg_659 = tmp_19_fu_474_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_555_p2.read()))) {
        next_mul2_reg_695 = next_mul2_fu_567_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        next_mul_reg_602 = next_mul_fu_356_p2.read();
        yi_3_reg_610 = yi_3_fu_368_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, or_cond7_fu_454_p2.read()))) {
        tmp_18_reg_654 = tmp_18_fu_588_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        xi_4_reg_690 = xi_4_fu_561_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        yi_4_reg_682 = yi_4_fu_549_p2.read();
    }
}

void filtrel_kernel::thread_Line_Flag2_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        Line_Flag2_address0 =  (sc_lv<5>) (tmp_20_fu_583_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        Line_Flag2_address0 = Line_Flag2_addr_reg_631.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        Line_Flag2_address0 =  (sc_lv<5>) (tmp_s_fu_413_p1.read());
    } else {
        Line_Flag2_address0 = "XXXXX";
    }
}

void filtrel_kernel::thread_Line_Flag2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        Line_Flag2_ce0 = ap_const_logic_1;
    } else {
        Line_Flag2_ce0 = ap_const_logic_0;
    }
}

void filtrel_kernel::thread_Line_Flag2_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        Line_Flag2_d0 = ap_const_lv1_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        Line_Flag2_d0 = ap_const_lv1_0;
    } else {
        Line_Flag2_d0 =  (sc_lv<1>) ("X");
    }
}

void filtrel_kernel::thread_Line_Flag2_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_401_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_fu_514_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_fu_537_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_19_reg_659.read())))) {
        Line_Flag2_we0 = ap_const_logic_1;
    } else {
        Line_Flag2_we0 = ap_const_logic_0;
    }
}

void filtrel_kernel::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void filtrel_kernel::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void filtrel_kernel::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void filtrel_kernel::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void filtrel_kernel::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void filtrel_kernel::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void filtrel_kernel::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void filtrel_kernel::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void filtrel_kernel::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void filtrel_kernel::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void filtrel_kernel::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void filtrel_kernel::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void filtrel_kernel::thread_ap_block_state11() {
    ap_block_state11 = ((esl_seteq<1,1,1>(ap_const_lv1_0, Line_Flag2_q0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())) || (esl_seteq<1,1,1>(Line_Flag2_q0.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())));
}

void filtrel_kernel::thread_ap_block_state4() {
    ap_block_state4 = (esl_seteq<1,1,1>(exitcond7_fu_374_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read()));
}

void filtrel_kernel::thread_ap_condition_260() {
    ap_condition_260 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && !((esl_seteq<1,1,1>(ap_const_lv1_0, Line_Flag2_q0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())) || (esl_seteq<1,1,1>(Line_Flag2_q0.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read()))));
}

void filtrel_kernel::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond8_fu_344_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void filtrel_kernel::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void filtrel_kernel::thread_ap_phi_mux_flag_be_phi_fu_302_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_fu_514_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_fu_537_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_19_reg_659.read()))) {
        ap_phi_mux_flag_be_phi_fu_302_p4 = ap_const_lv1_1;
    } else {
        ap_phi_mux_flag_be_phi_fu_302_p4 = flag_be_reg_297.read();
    }
}

void filtrel_kernel::thread_ap_phi_mux_temp_1_be_phi_fu_289_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_19_reg_659.read()))) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_fu_514_p2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_537_p2.read()))) {
            ap_phi_mux_temp_1_be_phi_fu_289_p4 = temp_1_reg_262.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_23_fu_514_p2.read())) {
            ap_phi_mux_temp_1_be_phi_fu_289_p4 = temp_3_fu_520_p2.read();
        } else {
            ap_phi_mux_temp_1_be_phi_fu_289_p4 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        ap_phi_mux_temp_1_be_phi_fu_289_p4 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void filtrel_kernel::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond8_fu_344_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void filtrel_kernel::thread_count_2_fu_350_p2() {
    count_2_fu_350_p2 = (!count_reg_172.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(count_reg_172.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void filtrel_kernel::thread_dst_data_stream_V_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(Line_Flag2_q0.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, Line_Flag2_q0.read())))) {
        dst_data_stream_V_blk_n = dst_data_stream_V_full_n.read();
    } else {
        dst_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void filtrel_kernel::thread_dst_data_stream_V_din() {
    if (esl_seteq<1,1,1>(ap_condition_260.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(Line_Flag2_q0.read(), ap_const_lv1_1)) {
            dst_data_stream_V_din = ap_const_lv8_0;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, Line_Flag2_q0.read())) {
            dst_data_stream_V_din = ap_const_lv8_FF;
        } else {
            dst_data_stream_V_din =  (sc_lv<8>) ("XXXXXXXX");
        }
    } else {
        dst_data_stream_V_din =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void filtrel_kernel::thread_dst_data_stream_V_write() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, Line_Flag2_q0.read()) && 
          !((esl_seteq<1,1,1>(ap_const_lv1_0, Line_Flag2_q0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())) || (esl_seteq<1,1,1>(Line_Flag2_q0.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(Line_Flag2_q0.read(), ap_const_lv1_1) && 
          !((esl_seteq<1,1,1>(ap_const_lv1_0, Line_Flag2_q0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())) || (esl_seteq<1,1,1>(Line_Flag2_q0.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())))))) {
        dst_data_stream_V_write = ap_const_logic_1;
    } else {
        dst_data_stream_V_write = ap_const_logic_0;
    }
}

void filtrel_kernel::thread_exitcond3_fu_555_p2() {
    exitcond3_fu_555_p2 = (!xi2_reg_322.read().is_01() || !ap_const_lv9_122.is_01())? sc_lv<1>(): sc_lv<1>(xi2_reg_322.read() == ap_const_lv9_122);
}

void filtrel_kernel::thread_exitcond4_fu_362_p2() {
    exitcond4_fu_362_p2 = (!yi_reg_183.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(yi_reg_183.read() == ap_const_lv4_A);
}

void filtrel_kernel::thread_exitcond6_fu_401_p2() {
    exitcond6_fu_401_p2 = (!i_reg_217.read().is_01() || !ap_const_lv5_1D.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_217.read() == ap_const_lv5_1D);
}

void filtrel_kernel::thread_exitcond7_fu_374_p2() {
    exitcond7_fu_374_p2 = (!xi_reg_206.read().is_01() || !ap_const_lv9_122.is_01())? sc_lv<1>(): sc_lv<1>(xi_reg_206.read() == ap_const_lv9_122);
}

void filtrel_kernel::thread_exitcond8_fu_344_p2() {
    exitcond8_fu_344_p2 = (!count_reg_172.read().is_01() || !ap_const_lv5_12.is_01())? sc_lv<1>(): sc_lv<1>(count_reg_172.read() == ap_const_lv5_12);
}

void filtrel_kernel::thread_exitcond_fu_543_p2() {
    exitcond_fu_543_p2 = (!yi1_reg_311.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(yi1_reg_311.read() == ap_const_lv4_A);
}

void filtrel_kernel::thread_i_2_fu_407_p2() {
    i_2_fu_407_p2 = (!i_reg_217.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_reg_217.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void filtrel_kernel::thread_icmp_fu_537_p2() {
    icmp_fu_537_p2 = (!tmp_13_fu_527_p4.read().is_01() || !ap_const_lv28_0.is_01())? sc_lv<1>(): (sc_bigint<28>(tmp_13_fu_527_p4.read()) > sc_bigint<28>(ap_const_lv28_0));
}

void filtrel_kernel::thread_j_2_fu_460_p2() {
    j_2_fu_460_p2 = (!j_reg_251.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(j_reg_251.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void filtrel_kernel::thread_k_2_fu_480_p2() {
    k_2_fu_480_p2 = (!k_reg_274.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(k_reg_274.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void filtrel_kernel::thread_k_cast8_cast_fu_470_p1() {
    k_cast8_cast_fu_470_p1 = esl_zext<7,4>(k_reg_274.read());
}

void filtrel_kernel::thread_line_buf1_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        line_buf1_address0 =  (sc_lv<12>) (p_sum_cast_fu_509_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        line_buf1_address0 =  (sc_lv<12>) (p_sum1_cast_fu_396_p1.read());
    } else {
        line_buf1_address0 =  (sc_lv<12>) ("XXXXXXXXXXXX");
    }
}

void filtrel_kernel::thread_line_buf1_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          !(esl_seteq<1,1,1>(exitcond7_fu_374_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read()))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        line_buf1_ce0 = ap_const_logic_1;
    } else {
        line_buf1_ce0 = ap_const_logic_0;
    }
}

void filtrel_kernel::thread_line_buf1_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(exitcond7_fu_374_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(exitcond7_fu_374_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read())))) {
        line_buf1_we0 = ap_const_logic_1;
    } else {
        line_buf1_we0 = ap_const_logic_0;
    }
}

void filtrel_kernel::thread_next_mul2_fu_567_p2() {
    next_mul2_fu_567_p2 = (!phi_mul2_reg_333.read().is_01() || !ap_const_lv18_334.is_01())? sc_lv<18>(): (sc_biguint<18>(phi_mul2_reg_333.read()) + sc_biguint<18>(ap_const_lv18_334));
}

void filtrel_kernel::thread_next_mul_fu_356_p2() {
    next_mul_fu_356_p2 = (!phi_mul_reg_194.read().is_01() || !ap_const_lv12_122.is_01())? sc_lv<12>(): (sc_biguint<12>(phi_mul_reg_194.read()) + sc_biguint<12>(ap_const_lv12_122));
}

void filtrel_kernel::thread_or_cond7_fu_454_p2() {
    or_cond7_fu_454_p2 = (tmp_16_fu_442_p2.read() & tmp_17_fu_448_p2.read());
}

void filtrel_kernel::thread_p_shl9_cast_cast_fu_438_p1() {
    p_shl9_cast_cast_fu_438_p1 = esl_zext<7,6>(p_shl9_fu_430_p3.read());
}

void filtrel_kernel::thread_p_shl9_fu_430_p3() {
    p_shl9_fu_430_p3 = esl_concat<5,1>(i_reg_217.read(), ap_const_lv1_0);
}

void filtrel_kernel::thread_p_shl_cast_fu_426_p1() {
    p_shl_cast_fu_426_p1 = esl_zext<9,8>(p_shl_fu_418_p3.read());
}

void filtrel_kernel::thread_p_shl_fu_418_p3() {
    p_shl_fu_418_p3 = esl_concat<5,3>(i_reg_217.read(), ap_const_lv3_0);
}

void filtrel_kernel::thread_p_sum1_cast_fu_396_p1() {
    p_sum1_cast_fu_396_p1 = esl_zext<64,12>(p_sum1_fu_390_p2.read());
}

void filtrel_kernel::thread_p_sum1_fu_390_p2() {
    p_sum1_fu_390_p2 = (!phi_mul_reg_194.read().is_01() || !tmp_54_cast_fu_386_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(phi_mul_reg_194.read()) + sc_biguint<12>(tmp_54_cast_fu_386_p1.read()));
}

void filtrel_kernel::thread_p_sum_cast_fu_509_p1() {
    p_sum_cast_fu_509_p1 = esl_sext<64,13>(p_sum_fu_504_p2.read());
}

void filtrel_kernel::thread_p_sum_fu_504_p2() {
    p_sum_fu_504_p2 = (!tmp_18_reg_654.read().is_01() || !tmp_61_cast_fu_500_p1.read().is_01())? sc_lv<13>(): (sc_bigint<13>(tmp_18_reg_654.read()) + sc_biguint<13>(tmp_61_cast_fu_500_p1.read()));
}

void filtrel_kernel::thread_src_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(exitcond7_fu_374_p2.read(), ap_const_lv1_0))) {
        src_data_stream_V_blk_n = src_data_stream_V_empty_n.read();
    } else {
        src_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void filtrel_kernel::thread_src_data_stream_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(exitcond7_fu_374_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(exitcond7_fu_374_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read())))) {
        src_data_stream_V_read = ap_const_logic_1;
    } else {
        src_data_stream_V_read = ap_const_logic_0;
    }
}

void filtrel_kernel::thread_temp_3_fu_520_p2() {
    temp_3_fu_520_p2 = (!temp_1_reg_262.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(temp_1_reg_262.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void filtrel_kernel::thread_tmp1_cast_fu_491_p1() {
    tmp1_cast_fu_491_p1 = esl_zext<9,7>(tmp1_fu_486_p2.read());
}

void filtrel_kernel::thread_tmp1_fu_486_p2() {
    tmp1_fu_486_p2 = (!p_shl9_cast_cast_reg_641.read().is_01() || !k_cast8_cast_fu_470_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(p_shl9_cast_cast_reg_641.read()) + sc_biguint<7>(k_cast8_cast_fu_470_p1.read()));
}

void filtrel_kernel::thread_tmp_12_fu_573_p4() {
    tmp_12_fu_573_p4 = phi_mul2_reg_333.read().range(17, 13);
}

void filtrel_kernel::thread_tmp_13_fu_527_p4() {
    tmp_13_fu_527_p4 = temp_1_reg_262.read().range(31, 4);
}

void filtrel_kernel::thread_tmp_16_fu_442_p2() {
    tmp_16_fu_442_p2 = (!j_reg_251.read().is_01() || !ap_const_lv32_A.is_01())? sc_lv<1>(): (sc_bigint<32>(j_reg_251.read()) < sc_bigint<32>(ap_const_lv32_A));
}

void filtrel_kernel::thread_tmp_17_fu_448_p2() {
    tmp_17_fu_448_p2 = (flag_reg_240.read() ^ ap_const_lv1_1);
}

void filtrel_kernel::thread_tmp_18_fu_588_p0() {
    tmp_18_fu_588_p0 =  (sc_lv<10>) (ap_const_lv13_122);
}

void filtrel_kernel::thread_tmp_18_fu_588_p1() {
    tmp_18_fu_588_p1 = j_reg_251.read().range(13-1, 0);
}

void filtrel_kernel::thread_tmp_19_fu_474_p2() {
    tmp_19_fu_474_p2 = (!k_reg_274.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): (sc_biguint<4>(k_reg_274.read()) < sc_biguint<4>(ap_const_lv4_A));
}

void filtrel_kernel::thread_tmp_20_fu_583_p1() {
    tmp_20_fu_583_p1 = esl_zext<64,5>(tmp_12_fu_573_p4.read());
}

void filtrel_kernel::thread_tmp_22_fu_495_p2() {
    tmp_22_fu_495_p2 = (!tmp1_cast_fu_491_p1.read().is_01() || !p_shl_cast_reg_636.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp1_cast_fu_491_p1.read()) + sc_biguint<9>(p_shl_cast_reg_636.read()));
}

void filtrel_kernel::thread_tmp_23_fu_514_p2() {
    tmp_23_fu_514_p2 = (!line_buf1_q0.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(line_buf1_q0.read() == ap_const_lv8_0);
}

void filtrel_kernel::thread_tmp_54_cast_fu_386_p1() {
    tmp_54_cast_fu_386_p1 = esl_zext<12,9>(xi_reg_206.read());
}

void filtrel_kernel::thread_tmp_61_cast_fu_500_p1() {
    tmp_61_cast_fu_500_p1 = esl_zext<13,9>(tmp_22_fu_495_p2.read());
}

void filtrel_kernel::thread_tmp_s_fu_413_p1() {
    tmp_s_fu_413_p1 = esl_zext<64,5>(i_reg_217.read());
}

void filtrel_kernel::thread_xi_3_fu_380_p2() {
    xi_3_fu_380_p2 = (!xi_reg_206.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(xi_reg_206.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void filtrel_kernel::thread_xi_4_fu_561_p2() {
    xi_4_fu_561_p2 = (!xi2_reg_322.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(xi2_reg_322.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void filtrel_kernel::thread_yi_3_fu_368_p2() {
    yi_3_fu_368_p2 = (!yi_reg_183.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(yi_reg_183.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void filtrel_kernel::thread_yi_4_fu_549_p2() {
    yi_4_fu_549_p2 = (!yi1_reg_311.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(yi1_reg_311.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void filtrel_kernel::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond8_fu_344_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond4_fu_362_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && !(esl_seteq<1,1,1>(exitcond7_fu_374_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read())) && esl_seteq<1,1,1>(exitcond7_fu_374_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond7_fu_374_p2.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(exitcond7_fu_374_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, src_data_stream_V_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond6_fu_401_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_454_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && ((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_23_fu_514_p2.read()) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, icmp_fu_537_p2.read())) || 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_reg_659.read())))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_543_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond3_fu_555_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && !((esl_seteq<1,1,1>(ap_const_lv1_0, Line_Flag2_q0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())) || (esl_seteq<1,1,1>(Line_Flag2_q0.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<11>) ("XXXXXXXXXXX");
            break;
    }
}

}

