// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _filtrel_kernel_HH_
#define _filtrel_kernel_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "TOP_fuct_mul_mul_mb6.h"
#include "filtrel_kernel_likbM.h"
#include "filtrel_kernel_LilbW.h"

namespace ap_rtl {

struct filtrel_kernel : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<8> > src_data_stream_V_dout;
    sc_in< sc_logic > src_data_stream_V_empty_n;
    sc_out< sc_logic > src_data_stream_V_read;
    sc_out< sc_lv<8> > dst_data_stream_V_din;
    sc_in< sc_logic > dst_data_stream_V_full_n;
    sc_out< sc_logic > dst_data_stream_V_write;


    // Module declarations
    filtrel_kernel(sc_module_name name);
    SC_HAS_PROCESS(filtrel_kernel);

    ~filtrel_kernel();

    sc_trace_file* mVcdFile;

    filtrel_kernel_likbM* line_buf1_U;
    filtrel_kernel_LilbW* Line_Flag2_U;
    TOP_fuct_mul_mul_mb6<1,1,10,13,13>* TOP_fuct_mul_mul_mb6_U99;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<11> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > src_data_stream_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > exitcond7_fu_374_p2;
    sc_signal< sc_logic > dst_data_stream_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<1> > Line_Flag2_q0;
    sc_signal< sc_lv<5> > count_2_fu_350_p2;
    sc_signal< sc_lv<5> > count_2_reg_597;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<12> > next_mul_fu_356_p2;
    sc_signal< sc_lv<12> > next_mul_reg_602;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<4> > yi_3_fu_368_p2;
    sc_signal< sc_lv<4> > yi_3_reg_610;
    sc_signal< sc_lv<9> > xi_3_fu_380_p2;
    sc_signal< bool > ap_block_state4;
    sc_signal< sc_lv<5> > i_2_fu_407_p2;
    sc_signal< sc_lv<5> > i_2_reg_626;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<5> > Line_Flag2_addr_reg_631;
    sc_signal< sc_lv<1> > exitcond6_fu_401_p2;
    sc_signal< sc_lv<9> > p_shl_cast_fu_426_p1;
    sc_signal< sc_lv<9> > p_shl_cast_reg_636;
    sc_signal< sc_lv<7> > p_shl9_cast_cast_fu_438_p1;
    sc_signal< sc_lv<7> > p_shl9_cast_cast_reg_641;
    sc_signal< sc_lv<32> > j_2_fu_460_p2;
    sc_signal< sc_lv<32> > j_2_reg_649;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<13> > tmp_18_fu_588_p2;
    sc_signal< sc_lv<13> > tmp_18_reg_654;
    sc_signal< sc_lv<1> > or_cond7_fu_454_p2;
    sc_signal< sc_lv<1> > tmp_19_fu_474_p2;
    sc_signal< sc_lv<1> > tmp_19_reg_659;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<4> > k_2_fu_480_p2;
    sc_signal< sc_lv<4> > k_2_reg_663;
    sc_signal< sc_lv<4> > yi_4_fu_549_p2;
    sc_signal< sc_lv<4> > yi_4_reg_682;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<9> > xi_4_fu_561_p2;
    sc_signal< sc_lv<9> > xi_4_reg_690;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<18> > next_mul2_fu_567_p2;
    sc_signal< sc_lv<18> > next_mul2_reg_695;
    sc_signal< sc_lv<1> > exitcond3_fu_555_p2;
    sc_signal< sc_lv<12> > line_buf1_address0;
    sc_signal< sc_logic > line_buf1_ce0;
    sc_signal< sc_logic > line_buf1_we0;
    sc_signal< sc_lv<8> > line_buf1_q0;
    sc_signal< sc_lv<5> > Line_Flag2_address0;
    sc_signal< sc_logic > Line_Flag2_ce0;
    sc_signal< sc_logic > Line_Flag2_we0;
    sc_signal< sc_lv<1> > Line_Flag2_d0;
    sc_signal< sc_lv<5> > count_reg_172;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<1> > exitcond_fu_543_p2;
    sc_signal< sc_lv<4> > yi_reg_183;
    sc_signal< sc_lv<1> > exitcond8_fu_344_p2;
    sc_signal< sc_lv<12> > phi_mul_reg_194;
    sc_signal< sc_lv<9> > xi_reg_206;
    sc_signal< sc_lv<1> > exitcond4_fu_362_p2;
    sc_signal< sc_lv<5> > i_reg_217;
    sc_signal< sc_lv<32> > temp_reg_228;
    sc_signal< sc_lv<32> > temp_1_reg_262;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<1> > tmp_23_fu_514_p2;
    sc_signal< sc_lv<1> > icmp_fu_537_p2;
    sc_signal< sc_lv<1> > flag_reg_240;
    sc_signal< sc_lv<1> > ap_phi_mux_flag_be_phi_fu_302_p4;
    sc_signal< sc_lv<32> > j_reg_251;
    sc_signal< sc_lv<32> > ap_phi_mux_temp_1_be_phi_fu_289_p4;
    sc_signal< sc_lv<4> > k_reg_274;
    sc_signal< sc_lv<32> > temp_3_fu_520_p2;
    sc_signal< sc_lv<1> > flag_be_reg_297;
    sc_signal< sc_lv<4> > yi1_reg_311;
    sc_signal< sc_lv<9> > xi2_reg_322;
    sc_signal< bool > ap_block_state11;
    sc_signal< sc_lv<18> > phi_mul2_reg_333;
    sc_signal< sc_lv<64> > p_sum1_cast_fu_396_p1;
    sc_signal< sc_lv<64> > tmp_s_fu_413_p1;
    sc_signal< sc_lv<64> > p_sum_cast_fu_509_p1;
    sc_signal< sc_lv<64> > tmp_20_fu_583_p1;
    sc_signal< sc_lv<12> > tmp_54_cast_fu_386_p1;
    sc_signal< sc_lv<12> > p_sum1_fu_390_p2;
    sc_signal< sc_lv<8> > p_shl_fu_418_p3;
    sc_signal< sc_lv<6> > p_shl9_fu_430_p3;
    sc_signal< sc_lv<1> > tmp_16_fu_442_p2;
    sc_signal< sc_lv<1> > tmp_17_fu_448_p2;
    sc_signal< sc_lv<7> > k_cast8_cast_fu_470_p1;
    sc_signal< sc_lv<7> > tmp1_fu_486_p2;
    sc_signal< sc_lv<9> > tmp1_cast_fu_491_p1;
    sc_signal< sc_lv<9> > tmp_22_fu_495_p2;
    sc_signal< sc_lv<13> > tmp_61_cast_fu_500_p1;
    sc_signal< sc_lv<13> > p_sum_fu_504_p2;
    sc_signal< sc_lv<28> > tmp_13_fu_527_p4;
    sc_signal< sc_lv<5> > tmp_12_fu_573_p4;
    sc_signal< sc_lv<10> > tmp_18_fu_588_p0;
    sc_signal< sc_lv<13> > tmp_18_fu_588_p1;
    sc_signal< sc_lv<11> > ap_NS_fsm;
    sc_signal< bool > ap_condition_260;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<11> ap_ST_fsm_state1;
    static const sc_lv<11> ap_ST_fsm_state2;
    static const sc_lv<11> ap_ST_fsm_state3;
    static const sc_lv<11> ap_ST_fsm_state4;
    static const sc_lv<11> ap_ST_fsm_state5;
    static const sc_lv<11> ap_ST_fsm_state6;
    static const sc_lv<11> ap_ST_fsm_state7;
    static const sc_lv<11> ap_ST_fsm_state8;
    static const sc_lv<11> ap_ST_fsm_state9;
    static const sc_lv<11> ap_ST_fsm_state10;
    static const sc_lv<11> ap_ST_fsm_state11;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<12> ap_const_lv12_0;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<18> ap_const_lv18_0;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<5> ap_const_lv5_12;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<12> ap_const_lv12_122;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<9> ap_const_lv9_122;
    static const sc_lv<9> ap_const_lv9_1;
    static const sc_lv<5> ap_const_lv5_1D;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<28> ap_const_lv28_0;
    static const sc_lv<18> ap_const_lv18_334;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<13> ap_const_lv13_122;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_Line_Flag2_address0();
    void thread_Line_Flag2_ce0();
    void thread_Line_Flag2_d0();
    void thread_Line_Flag2_we0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_block_state1();
    void thread_ap_block_state11();
    void thread_ap_block_state4();
    void thread_ap_condition_260();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_flag_be_phi_fu_302_p4();
    void thread_ap_phi_mux_temp_1_be_phi_fu_289_p4();
    void thread_ap_ready();
    void thread_count_2_fu_350_p2();
    void thread_dst_data_stream_V_blk_n();
    void thread_dst_data_stream_V_din();
    void thread_dst_data_stream_V_write();
    void thread_exitcond3_fu_555_p2();
    void thread_exitcond4_fu_362_p2();
    void thread_exitcond6_fu_401_p2();
    void thread_exitcond7_fu_374_p2();
    void thread_exitcond8_fu_344_p2();
    void thread_exitcond_fu_543_p2();
    void thread_i_2_fu_407_p2();
    void thread_icmp_fu_537_p2();
    void thread_j_2_fu_460_p2();
    void thread_k_2_fu_480_p2();
    void thread_k_cast8_cast_fu_470_p1();
    void thread_line_buf1_address0();
    void thread_line_buf1_ce0();
    void thread_line_buf1_we0();
    void thread_next_mul2_fu_567_p2();
    void thread_next_mul_fu_356_p2();
    void thread_or_cond7_fu_454_p2();
    void thread_p_shl9_cast_cast_fu_438_p1();
    void thread_p_shl9_fu_430_p3();
    void thread_p_shl_cast_fu_426_p1();
    void thread_p_shl_fu_418_p3();
    void thread_p_sum1_cast_fu_396_p1();
    void thread_p_sum1_fu_390_p2();
    void thread_p_sum_cast_fu_509_p1();
    void thread_p_sum_fu_504_p2();
    void thread_src_data_stream_V_blk_n();
    void thread_src_data_stream_V_read();
    void thread_temp_3_fu_520_p2();
    void thread_tmp1_cast_fu_491_p1();
    void thread_tmp1_fu_486_p2();
    void thread_tmp_12_fu_573_p4();
    void thread_tmp_13_fu_527_p4();
    void thread_tmp_16_fu_442_p2();
    void thread_tmp_17_fu_448_p2();
    void thread_tmp_18_fu_588_p0();
    void thread_tmp_18_fu_588_p1();
    void thread_tmp_19_fu_474_p2();
    void thread_tmp_20_fu_583_p1();
    void thread_tmp_22_fu_495_p2();
    void thread_tmp_23_fu_514_p2();
    void thread_tmp_54_cast_fu_386_p1();
    void thread_tmp_61_cast_fu_500_p1();
    void thread_tmp_s_fu_413_p1();
    void thread_xi_3_fu_380_p2();
    void thread_xi_4_fu_561_p2();
    void thread_yi_3_fu_368_p2();
    void thread_yi_4_fu_549_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
