// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "ListInsert.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic ListInsert::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic ListInsert::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> ListInsert::ap_ST_fsm_state1 = "1";
const sc_lv<3> ListInsert::ap_ST_fsm_state2 = "10";
const sc_lv<3> ListInsert::ap_ST_fsm_state3 = "100";
const sc_lv<32> ListInsert::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> ListInsert::ap_const_lv1_0 = "0";
const sc_lv<1> ListInsert::ap_const_lv1_1 = "1";
const sc_lv<32> ListInsert::ap_const_lv32_1 = "1";
const sc_lv<32> ListInsert::ap_const_lv32_2 = "10";
const sc_lv<32> ListInsert::ap_const_lv32_1388 = "1001110001000";
const sc_lv<32> ListInsert::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const bool ListInsert::ap_const_boolean_1 = true;

ListInsert::ListInsert(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Data_address0);
    sensitive << ( tmp_reg_151 );
    sensitive << ( tmp_62_reg_155 );
    sensitive << ( tmp_63_reg_159 );
    sensitive << ( Data_addr_reg_163 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_65_fu_109_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_68_fu_120_p1 );
    sensitive << ( tmp_67_fu_130_p1 );

    SC_METHOD(thread_Data_ce0);
    sensitive << ( tmp_reg_151 );
    sensitive << ( tmp_62_reg_155 );
    sensitive << ( tmp_63_reg_159 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_65_fu_109_p2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_Data_d0);
    sensitive << ( Data_q0 );
    sensitive << ( e_cast_reg_146 );
    sensitive << ( tmp_reg_151 );
    sensitive << ( tmp_62_reg_155 );
    sensitive << ( tmp_63_reg_159 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_65_fu_109_p2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_Data_we0);
    sensitive << ( tmp_reg_151 );
    sensitive << ( tmp_62_reg_155 );
    sensitive << ( tmp_63_reg_159 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_65_fu_109_p2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_reg_151 );
    sensitive << ( tmp_62_reg_155 );
    sensitive << ( tmp_63_reg_159 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_65_fu_109_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( tmp_reg_151 );
    sensitive << ( tmp_62_reg_155 );
    sensitive << ( tmp_63_reg_159 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_65_fu_109_p2 );

    SC_METHOD(thread_e_cast_fu_76_p1);
    sensitive << ( e );

    SC_METHOD(thread_j_6_fu_114_p2);
    sensitive << ( j_reg_67 );

    SC_METHOD(thread_tmp_62_fu_92_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( i );
    sensitive << ( tmp_fu_80_p2 );
    sensitive << ( tmp_s_fu_86_p2 );

    SC_METHOD(thread_tmp_63_fu_98_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( length_r );
    sensitive << ( tmp_fu_80_p2 );
    sensitive << ( tmp_62_fu_92_p2 );

    SC_METHOD(thread_tmp_64_fu_104_p1);
    sensitive << ( i );

    SC_METHOD(thread_tmp_65_fu_109_p2);
    sensitive << ( i );
    sensitive << ( tmp_reg_151 );
    sensitive << ( tmp_62_reg_155 );
    sensitive << ( tmp_63_reg_159 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( j_reg_67 );

    SC_METHOD(thread_tmp_66_fu_125_p2);
    sensitive << ( i );

    SC_METHOD(thread_tmp_67_fu_130_p1);
    sensitive << ( tmp_66_fu_125_p2 );

    SC_METHOD(thread_tmp_68_fu_120_p1);
    sensitive << ( j_6_fu_114_p2 );

    SC_METHOD(thread_tmp_fu_80_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( i );

    SC_METHOD(thread_tmp_s_fu_86_p2);
    sensitive << ( length_r );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_reg_151 );
    sensitive << ( tmp_62_reg_155 );
    sensitive << ( tmp_63_reg_159 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_65_fu_109_p2 );

    ap_CS_fsm = "001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "ListInsert_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, Data_address0, "(port)Data_address0");
    sc_trace(mVcdFile, Data_ce0, "(port)Data_ce0");
    sc_trace(mVcdFile, Data_we0, "(port)Data_we0");
    sc_trace(mVcdFile, Data_d0, "(port)Data_d0");
    sc_trace(mVcdFile, Data_q0, "(port)Data_q0");
    sc_trace(mVcdFile, i, "(port)i");
    sc_trace(mVcdFile, e, "(port)e");
    sc_trace(mVcdFile, length_r, "(port)length_r");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, e_cast_fu_76_p1, "e_cast_fu_76_p1");
    sc_trace(mVcdFile, e_cast_reg_146, "e_cast_reg_146");
    sc_trace(mVcdFile, tmp_fu_80_p2, "tmp_fu_80_p2");
    sc_trace(mVcdFile, tmp_reg_151, "tmp_reg_151");
    sc_trace(mVcdFile, tmp_62_fu_92_p2, "tmp_62_fu_92_p2");
    sc_trace(mVcdFile, tmp_62_reg_155, "tmp_62_reg_155");
    sc_trace(mVcdFile, tmp_63_fu_98_p2, "tmp_63_fu_98_p2");
    sc_trace(mVcdFile, tmp_63_reg_159, "tmp_63_reg_159");
    sc_trace(mVcdFile, Data_addr_reg_163, "Data_addr_reg_163");
    sc_trace(mVcdFile, j_6_fu_114_p2, "j_6_fu_114_p2");
    sc_trace(mVcdFile, j_6_reg_171, "j_6_reg_171");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_65_fu_109_p2, "tmp_65_fu_109_p2");
    sc_trace(mVcdFile, j_reg_67, "j_reg_67");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_64_fu_104_p1, "tmp_64_fu_104_p1");
    sc_trace(mVcdFile, tmp_68_fu_120_p1, "tmp_68_fu_120_p1");
    sc_trace(mVcdFile, tmp_67_fu_130_p1, "tmp_67_fu_130_p1");
    sc_trace(mVcdFile, tmp_s_fu_86_p2, "tmp_s_fu_86_p2");
    sc_trace(mVcdFile, tmp_66_fu_125_p2, "tmp_66_fu_125_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

ListInsert::~ListInsert() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void ListInsert::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(tmp_fu_80_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(tmp_62_fu_92_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(tmp_63_fu_98_p2.read(), ap_const_lv1_1))) {
        j_reg_67 = length_r.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_reg_67 = j_6_reg_171.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(tmp_fu_80_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_62_fu_92_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_63_fu_98_p2.read(), ap_const_lv1_1))) {
        Data_addr_reg_163 =  (sc_lv<13>) (tmp_64_fu_104_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        e_cast_reg_146 = e_cast_fu_76_p1.read();
        tmp_reg_151 = tmp_fu_80_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_reg_151.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_62_reg_155.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_63_reg_159.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_65_fu_109_p2.read()))) {
        j_6_reg_171 = j_6_fu_114_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(tmp_fu_80_p2.read(), ap_const_lv1_0))) {
        tmp_62_reg_155 = tmp_62_fu_92_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(tmp_fu_80_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_62_fu_92_p2.read(), ap_const_lv1_0))) {
        tmp_63_reg_159 = tmp_63_fu_98_p2.read();
    }
}

void ListInsert::thread_Data_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        Data_address0 = Data_addr_reg_163.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(tmp_reg_151.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_62_reg_155.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_63_reg_159.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_65_fu_109_p2.read()))) {
        Data_address0 =  (sc_lv<13>) (tmp_67_fu_130_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(tmp_reg_151.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_62_reg_155.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_63_reg_159.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_65_fu_109_p2.read()))) {
        Data_address0 =  (sc_lv<13>) (tmp_68_fu_120_p1.read());
    } else {
        Data_address0 = "XXXXXXXXXXXXX";
    }
}

void ListInsert::thread_Data_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(tmp_reg_151.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_62_reg_155.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_63_reg_159.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_65_fu_109_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(tmp_reg_151.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_62_reg_155.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_63_reg_159.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_65_fu_109_p2.read())))) {
        Data_ce0 = ap_const_logic_1;
    } else {
        Data_ce0 = ap_const_logic_0;
    }
}

void ListInsert::thread_Data_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        Data_d0 = Data_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(tmp_reg_151.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_62_reg_155.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_63_reg_159.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_65_fu_109_p2.read()))) {
        Data_d0 = e_cast_reg_146.read();
    } else {
        Data_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void ListInsert::thread_Data_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(tmp_reg_151.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_62_reg_155.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_63_reg_159.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_65_fu_109_p2.read())))) {
        Data_we0 = ap_const_logic_1;
    } else {
        Data_we0 = ap_const_logic_0;
    }
}

void ListInsert::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void ListInsert::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void ListInsert::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void ListInsert::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          (((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_65_fu_109_p2.read()) || 
             esl_seteq<1,1,1>(ap_const_lv1_0, tmp_63_reg_159.read())) || 
            esl_seteq<1,1,1>(tmp_62_reg_155.read(), ap_const_lv1_1)) || 
           esl_seteq<1,1,1>(tmp_reg_151.read(), ap_const_lv1_1))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void ListInsert::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void ListInsert::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         (((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_65_fu_109_p2.read()) || 
            esl_seteq<1,1,1>(ap_const_lv1_0, tmp_63_reg_159.read())) || 
           esl_seteq<1,1,1>(tmp_62_reg_155.read(), ap_const_lv1_1)) || 
          esl_seteq<1,1,1>(tmp_reg_151.read(), ap_const_lv1_1)))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void ListInsert::thread_e_cast_fu_76_p1() {
    e_cast_fu_76_p1 = esl_zext<32,9>(e.read());
}

void ListInsert::thread_j_6_fu_114_p2() {
    j_6_fu_114_p2 = (!j_reg_67.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(j_reg_67.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void ListInsert::thread_tmp_62_fu_92_p2() {
    tmp_62_fu_92_p2 = (!tmp_s_fu_86_p2.read().is_01() || !i.read().is_01())? sc_lv<1>(): (sc_bigint<32>(tmp_s_fu_86_p2.read()) < sc_bigint<32>(i.read()));
}

void ListInsert::thread_tmp_63_fu_98_p2() {
    tmp_63_fu_98_p2 = (!length_r.read().is_01() || !ap_const_lv32_1388.is_01())? sc_lv<1>(): (sc_bigint<32>(length_r.read()) < sc_bigint<32>(ap_const_lv32_1388));
}

void ListInsert::thread_tmp_64_fu_104_p1() {
    tmp_64_fu_104_p1 = esl_zext<64,32>(i.read());
}

void ListInsert::thread_tmp_65_fu_109_p2() {
    tmp_65_fu_109_p2 = (!j_reg_67.read().is_01() || !i.read().is_01())? sc_lv<1>(): (sc_bigint<32>(j_reg_67.read()) < sc_bigint<32>(i.read()));
}

void ListInsert::thread_tmp_66_fu_125_p2() {
    tmp_66_fu_125_p2 = (!i.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(i.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void ListInsert::thread_tmp_67_fu_130_p1() {
    tmp_67_fu_130_p1 = esl_zext<64,32>(tmp_66_fu_125_p2.read());
}

void ListInsert::thread_tmp_68_fu_120_p1() {
    tmp_68_fu_120_p1 = esl_zext<64,32>(j_6_fu_114_p2.read());
}

void ListInsert::thread_tmp_fu_80_p2() {
    tmp_fu_80_p2 = (!i.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<1>(): (sc_bigint<32>(i.read()) < sc_bigint<32>(ap_const_lv32_1));
}

void ListInsert::thread_tmp_s_fu_86_p2() {
    tmp_s_fu_86_p2 = (!length_r.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(length_r.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void ListInsert::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && (((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_65_fu_109_p2.read()) || 
    esl_seteq<1,1,1>(ap_const_lv1_0, tmp_63_reg_159.read())) || 
   esl_seteq<1,1,1>(tmp_62_reg_155.read(), ap_const_lv1_1)) || 
  esl_seteq<1,1,1>(tmp_reg_151.read(), ap_const_lv1_1)))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<3>) ("XXX");
            break;
    }
}

}

