// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Loop_memset_XsOvImSt.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Loop_memset_XsOvImSt::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Loop_memset_XsOvImSt::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> Loop_memset_XsOvImSt::ap_ST_fsm_state1 = "1";
const sc_lv<2> Loop_memset_XsOvImSt::ap_ST_fsm_state2 = "10";
const sc_lv<32> Loop_memset_XsOvImSt::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> Loop_memset_XsOvImSt::ap_const_lv32_1 = "1";
const sc_lv<1> Loop_memset_XsOvImSt::ap_const_lv1_0 = "0";
const sc_lv<1> Loop_memset_XsOvImSt::ap_const_lv1_1 = "1";
const bool Loop_memset_XsOvImSt::ap_const_boolean_1 = true;

Loop_memset_XsOvImSt::Loop_memset_XsOvImSt(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_XsOvImStrtLoc_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_s_fu_41_p1 );

    SC_METHOD(thread_XsOvImStrtLoc_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_XsOvImStrtLoc_d0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_XsOvImStrtLoc_we0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_invdar1_phi_fu_34_p4 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_invdar1_phi_fu_34_p4);
    sensitive << ( invdar1_reg_30 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_invdar1_phi_fu_34_p4 );

    SC_METHOD(thread_indvarinc1_fu_46_p2);
    sensitive << ( invdar1_reg_30 );

    SC_METHOD(thread_tmp_s_fu_41_p1);
    sensitive << ( invdar1_reg_30 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_phi_mux_invdar1_phi_fu_34_p4 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Loop_memset_XsOvImSt_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, XsOvImStrtLoc_address0, "(port)XsOvImStrtLoc_address0");
    sc_trace(mVcdFile, XsOvImStrtLoc_ce0, "(port)XsOvImStrtLoc_ce0");
    sc_trace(mVcdFile, XsOvImStrtLoc_we0, "(port)XsOvImStrtLoc_we0");
    sc_trace(mVcdFile, XsOvImStrtLoc_d0, "(port)XsOvImStrtLoc_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvarinc1_fu_46_p2, "indvarinc1_fu_46_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_phi_mux_invdar1_phi_fu_34_p4, "ap_phi_mux_invdar1_phi_fu_34_p4");
    sc_trace(mVcdFile, invdar1_reg_30, "invdar1_reg_30");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, tmp_s_fu_41_p1, "tmp_s_fu_41_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

Loop_memset_XsOvImSt::~Loop_memset_XsOvImSt() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void Loop_memset_XsOvImSt::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_phi_mux_invdar1_phi_fu_34_p4.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_phi_mux_invdar1_phi_fu_34_p4.read()))) {
        invdar1_reg_30 = indvarinc1_fu_46_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        invdar1_reg_30 = ap_const_lv1_0;
    }
}

void Loop_memset_XsOvImSt::thread_XsOvImStrtLoc_address0() {
    XsOvImStrtLoc_address0 =  (sc_lv<1>) (tmp_s_fu_41_p1.read());
}

void Loop_memset_XsOvImSt::thread_XsOvImStrtLoc_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        XsOvImStrtLoc_ce0 = ap_const_logic_1;
    } else {
        XsOvImStrtLoc_ce0 = ap_const_logic_0;
    }
}

void Loop_memset_XsOvImSt::thread_XsOvImStrtLoc_d0() {
    XsOvImStrtLoc_d0 = ap_const_lv1_0;
}

void Loop_memset_XsOvImSt::thread_XsOvImStrtLoc_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        XsOvImStrtLoc_we0 = ap_const_logic_1;
    } else {
        XsOvImStrtLoc_we0 = ap_const_logic_0;
    }
}

void Loop_memset_XsOvImSt::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Loop_memset_XsOvImSt::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Loop_memset_XsOvImSt::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void Loop_memset_XsOvImSt::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_phi_mux_invdar1_phi_fu_34_p4.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Loop_memset_XsOvImSt::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Loop_memset_XsOvImSt::thread_ap_phi_mux_invdar1_phi_fu_34_p4() {
    ap_phi_mux_invdar1_phi_fu_34_p4 = invdar1_reg_30.read();
}

void Loop_memset_XsOvImSt::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_phi_mux_invdar1_phi_fu_34_p4.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Loop_memset_XsOvImSt::thread_indvarinc1_fu_46_p2() {
    indvarinc1_fu_46_p2 = (invdar1_reg_30.read() ^ ap_const_lv1_1);
}

void Loop_memset_XsOvImSt::thread_tmp_s_fu_41_p1() {
    tmp_s_fu_41_p1 = esl_zext<64,1>(invdar1_reg_30.read());
}

void Loop_memset_XsOvImSt::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_phi_mux_invdar1_phi_fu_34_p4.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

